### PR TITLE
New: Fix keras model importing bug when tensorflow scope used

### PR DESCRIPTION
**Pull request by zheolong**
## What changes were proposed in this pull request?

fix issues/3597, the keras model loading bug, when tensorflow scope used 

My method is parsing the 'nested' group structure from h5 or weight file like below.

default

## How was this patch tested?

unit test, test cases:

1. loading single h5 file without tensorflow scope
2. loading weight file and json file without tensorflow scope
3. loading single h5 file with tensorflow scope
4. loading weight file and json file with tensorflow scope

[model_files_for_test.tar.gz](https://github.com/deeplearning4j/deeplearning4j/files/1217845/model_files_for_test.tar.gz)

### CODE REVIEW

**Comment by maxpumperla** [comment]
@zheolong hmm, I'm not sure splitting strings in half will do... this depends entirely on having 2 sets of weights. Does this pass all the tests?

**Comment by maxpumperla** [comment]
what still bothers me most in the original approach is that the logic changed: 

```
//                            ? weightsArchive.getDataSets(weightsRoot, layerName + "/" + layerFragments[0])
//                            : weightsArchive.getDataSets(layerName + "/" + layerFragments[0]);
                                    ? weightsArchive.getDataSets(weightsRoot, layerName + "/" + attributeJoinStr)
                                    : weightsArchive.getDataSets(layerName + "/" + attributeJoinStr);
```
here attributeJoinStr takes the role of layerFragments[0]. A few lines down we have 

```
                        ? weightsArchive.getDataSets(weightsRoot, layerName)
                        : weightsArchive.getDataSets(layerName);
//                                ? weightsArchive.getDataSets(weightsRoot, layerName + "/" + attributeJoinStr)
//                                : weightsArchive.getDataSets(layerName + "/" + attributeJoinStr);
```
i.e. we **add** attributeJoinStr where it hasn't been before.

**Comment by maxpumperla** [comment]
This requires a lot of special knowledge to juggle in your head to make sense of it. Usually it's places like these you will suffer for later on.

**Comment by zheolong** [comment]
@maxpumperla splitting strings in half is a trick but only way I figure out. I've tested it.

**Comment by maxpumperla** [comment]
OK, I think I found a way to address this that is a little more stable (still not great). Will have to reject this PR and open another. Thanks for looking into this, though. Was still very helpful to discuss. thanks again

**Comment by zheolong** [comment]
@maxpumperla ok, when u did it, let me know please

**Comment by maxpumperla** [comment]
@zheolong  I did already, see #3862. However, people seem to have a little trouble with it still. Tests run again, but I need to review this once more.

**Pull request closed without merging**
