### PR TITLE
RL4J - Made a few fixes

### PR DESCRIPTION
**Pull request by aboulang2002**
## What changes were proposed in this pull request?

As I am figuring out how to change the way observations are handled in RL4J, I found and fixed a few issues:

Changes to ObservationSpace and ActionSpace:
- DiscreteSpace did not use org.nd4j.linalg.api.rng.Random
- Moved ObservationSpace, ActionSpace, DiscreteSpace and ArrayObservationSpace to rl4j-core
- Removed setSeed from ActionSpace (since we are now using an already seeded Random via Nd4J.getRandom())
- Added setRandom to ActionSpace to help unit tests

Changes to initMDP:
- initMDP did not check if !mdp.isDone()
- In initMDP(), the history was being filled with only the initial observation. i.e. the very first observation was continuously fed to HistoryProcessor.add() instead of the current one (nextO)

Other:
- The last observation of an epoch was not being recorded (HistoryProcessor.record())
    - Changed QLearningDiscrete, Policy.play()
	- ~~Did not change AsyncThreadDiscrete. To be done in another PR; I don't want to change anything in this class before it's unit tested.~~
	- Added refac unit tests to Policy.play(). Note: It seems weird that it's the policy that has the play() method. There should be an Agent class. To be done later.

## How was this patch tested?

Unit tests and manual tests

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [X] Created tests for any significant new code additions.
- [X] Relevant tests for your changes are passing.

### CODE REVIEW

**Comment by saudet** [comment]
We can't move ObservationSpace, etc from gym-java-client because that creates circular dependencies. The plan is to get rid of gym-java-client, but for the moment please just leave it like it is now.

**Comment by aboulang2002** [comment]
I reverted the move of ObservationSpace, ActionSpace and others from gym-java-client. Sorry for missing the circular dependency.

**Comment by aboulang2002** [comment]
Added a unit test to `AsyncThreadDiscrete` and a few others.
AsyncThreadDiscrete seems to record all observations after all.

**Comment by saudet** [comment]
We can still make the modifications to the ones in gym-java-client though. Those will get moved later, so might as well make the changes there now.

**Comment by aboulang2002** [comment]
Good idea. I made the changes.

**Review by saudet — APPROVED** [review]
Confirmed working with the A3CALE and Cartpole examples.

**Pull request merged**
