### PR TITLE
225: have two options for fitting, one that is async and one not.

### PR DESCRIPTION
**Pull request by Bam4d**
user can choose how to process. and a second blocking call that implements a countdown latch for each batch. fixes parts of #225

### CODE REVIEW

**Comment by Bam4d** [comment]
Incorrect implementation, please ignore

**Comment by agibsonccc** [comment]
Updates on this? I'm getting ready for a release here in the next week or so (the last feature I need is opencl support in nd4j) and checking some of the other models. It'd be great to get this mainlined.

**Comment by Bam4d** [comment]
As far as I'm concerned the implementation works for me, I don't know why the build is failing however.

If you're happy with it go for it.

**Comment by Bam4d** [comment]
The only thing I have to say is that I couldn't test it working with GPU due to the bug I posted in the google group https://groups.google.com/forum/#!topic/deeplearning4j/0m5s4Qkjc-I. I wouldn't be related to this PR however.

**Pull request merged**
