### PR TITLE
proper close streams

### PR DESCRIPTION
**Pull request by turbanoff**
## What changes were proposed in this pull request?
Properly close file output/input streams

## How was this patch tested?
Not tested

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Reviewed the [Contributing Guidelines](https://github.com/deeplearning4j/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.
- [ ] Ran mvn formatter:format (see [formatter instructions](http://code.revelc.net/formatter-maven-plugin/examples.html#Setting_Source_Files) for targeting your specific files).

### CODE REVIEW

**Comment by turbanoff** [comment]
@raver119 As I can see it was already used. Should I refactor to use `commons-io` instead?

**Comment by raver119** [comment]
As i remember, we were removing these uses on demand... If you have some free time and willing to do that - that would be just amazing.

**Comment by agibsonccc** [comment]
@raver119 Any reason we haven't merged this yet?

**Comment by raver119** [comment]
None actually. I've just missed update notifications.

**Pull request merged**
