### PR TITLE
restoreMultiLayerNetwork() needlessly writes temp-file #8735

### PR DESCRIPTION
**Pull request by horschi**
## What changes were proposed in this pull request?
Proposed fix for #8735 restoreMultiLayerNetwork() needlessly writes temp-file.

## How was this patch tested?
I have trouble building DL4j from source. I have tested the changes with my application, but I have not run any automated tests.

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

### CODE REVIEW

**Comment by raver119** [comment]
@AlexDBlack @saudet what can we do in order to fix jcpp snapshots issue in eclipse repo?

**Comment by saudet** [comment]
@raver119 Could you clarify what this has to do with JavaCPP?

**Comment by AlexDBlack** [comment]
@horschi Thanks for the PR and apologies for the delay.
Closing this in favor of: https://github.com/eclipse/deeplearning4j/pull/8815 (you'll still get credit for the commit)

Needed a few small fixes (non-closed streams, couple of test failures), but otherwise was great.

**Comment by horschi** [comment]
@AlexDBlack That's alright. I'm happy the issue gets resolved :-)

**Pull request closed without merging**
