### PR TITLE
Fix global pooling for NWC/NCW channel variants

### PR DESCRIPTION
**Pull request by agibsonccc**
## What changes were proposed in this pull request?
Fixes global pooling to work with different dimension orders.
(Please fill in changes proposed in this fix)

## How was this patch tested?
Manual, also will add test
(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [X ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [X ] Created tests for any significant new code additions.
- [ X] Relevant tests for your changes are passing.

### CODE REVIEW

**Comment by joel-a** [comment]
@agibsonccc Thanks for taking care of this. I assume that a reviewer will be assigned to this request soon and the fix will be merged to master. In any case, I'm still having issues importing my Keras model. I split it into sections to bypass the InputType errors and test the different parts of the model in DL4J, the current error is:

```
Exception in thread "main" org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Cannot assign arrays: arrays must both be scalars, both vectors, or shapes must be equal other than size 1 dimensions. Attempting to do x.assign(y) with x.shape=[128, 8000, 160, 1] and y.shape=[160, 1, 128, 1]
Tried to set weights for layer with name conv1d_2, of class org.deeplearning4j.nn.conf.layers.Convolution1DLayer.
Failed to set weights for parameter W
Expected shape for this parameter: Rank: 4, DataType: FLOAT, Offset: 0, Order: c, Shape: [128,8000,160,1],  Stride: [1280000,160,1,1], 
got: Rank: 4, DataType: FLOAT, Offset: 0, Order: c, Shape: [160,1,128,1],  Stride: [128,128,1,1]. For more information, see https://deeplearning4j.konduit.ai/keras-import/overview
	at org.deeplearning4j.nn.modelimport.keras.KerasLayer.copyWeightsToLayer(KerasLayer.java:355)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelUtils.copyWeightsToModel(KerasModelUtils.java:74)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:638)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:624)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:168)
```

It is triggered by the following model (.h5 attached):
```
from keras.regularizers import l2
in_feats = Input(shape=(8000, 1))
enc_layer = Conv1D(128, 160, strides=20, input_shape=(1, 8000),
                   padding='same',activation='relu', use_bias=False, kernel_regularizer=l2(1e-5))
enc = enc_layer(in_feats)
encoder_model = Model(in_feats,enc)
encoder_model.summary()
encoder_model.save("testEncoder.h5")
```

As usual, in Java I'm loading the model with:
```
encoderPath = "testEncoder.h5";
encoder = KerasModelImport.importKerasModelAndWeights(encoderPath);
```

Any help in fixing this will be greatly appreciated. Thank you!

[testEncoder.zip](https://github.com/eclipse/deeplearning4j/files/6682537/testEncoder.zip)

**Comment by agibsonccc** [comment]
@joel-a 
You have the basic idea yes.
Regarding your next error, that appears to be a shape mismatch (possibly also due to expected weight layouts) - let me look at your reproducer really fast and get that up today too.

**Comment by agibsonccc** [comment]
@joel-a sorry didn't get to look at this fully today, but after running it for a minute I noticed both an input_shape definition on your conv1d and an Input of 8000,1. If I remove the input_shape from conv1d it actually imports fine. Was there a reason for the duplicate input_shape?

**Comment by joel-a** [comment]
@agibsonccc That was an oversight from my part; there's no need for specifying the input_shape parameter. My apologies and thank you for catching that!

**Review by treo — APPROVED** [review]

**Comment by joel-a** [comment]
@agibsonccc After this fix, I'm getting a different error when loading GAPError.h5
```
Exception in thread "main" org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: ElementWise vertex cannot process activations of different types: first type = FF, input type 2 = RNN
	at org.deeplearning4j.nn.conf.graph.ElementWiseVertex.getOutputType(ElementWiseVertex.java:134)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.getLayerActivationTypes(ComputationGraphConfiguration.java:567)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.addPreProcessors(ComputationGraphConfiguration.java:458)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraphConfiguration(KerasModel.java:613)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:635)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.getComputationGraph(KerasModel.java:624)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasModelAndWeights(KerasModelImport.java:168)
```

In your test, are you using the model as I provided it in GAPError.h5? Any help with this will be greatly appreciated.

Thank you!

**Comment by agibsonccc** [comment]
@joel-a let me rerun it with all the new changes incorporated, I do remember running in to that already and fixing it though.  Edit: Ah I remember this. It didn't happen every time. I was working on making that reproduce consistently. Eg: If I run it in the debugger I'm seeing:
```bash
.d.n.g.ComputationGraph - Starting ComputationGraph with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
Rank: 3, DataType: FLOAT, Offset: 0, Order: c, Shape: [1,400,512],  Stride: [204800,512,1]
```

My test is simple:
```java
 ComputationGraph computationGraph = KerasModelImport.importKerasModelAndWeights("GAPError.h5");
        INDArray input = Nd4j.ones(1,400,128);
        INDArray[] output = computationGraph.output(input);
        System.out.println(output[0].shapeInfoToString());
```

**Comment by agibsonccc** [comment]
@joel-a  I think I nailed the reproducibility issue here. Running tests and polish now: https://github.com/eclipse/deeplearning4j/pull/9384 The main issue was the global pooling layer returning a feed forward type when we collapse dimensions (which keras does by default ) - since global pooling is mainly used with rnn anyways I just migrated the input type to rnn. I'll see how this pans out in the tests and try to map out the side effects of this before merging it.

**Pull request merged**
