### PR TITLE
Fix Arrow Flatbuffers version / incompatibility

### PR DESCRIPTION
**Pull request by AlexDBlack**
Fixes: https://github.com/deeplearning4j/deeplearning4j/issues/6372
Also upgrades to arrow 0.10.0 - seems no changes on our end were required for this.

How this works:
- Add org.nd4j:flatbuffers:
    - One relocation: com.google.flatbuffers.FlatFlatBuffersBuilder to org.nd4j.shade.FlatBufferBuilder. All other classes are not relocated/changed (but obviously are included in the shaded JAR)
    - Add new class: org.nd4j.flatbuffers.FlatBufferBuilder extends com.google.flatbuffers.FlatFlatBuffersBuilder with 1 new method. Shaded to com.google.flatbuffers.FlatFlatBuffersBuilder during the build
- Arrow's flatbuffer dependency (com.vlkan:flatbuffers) is excluded
- nd4j-api, nd4j-arrow and datavec-arrow now use org.nd4j:flatbuffers

### CODE REVIEW

**Comment by agibsonccc** [comment]
@AlexDBlack where are we with this?

**Comment by AlexDBlack** [comment]
@agibsonccc Blocked. The fix works fine, but it fails every time on CI.
The problem is that when we run the build separately from the tests, the test classpath is wrong - it still includes the original flatbuffers dependency (and not the shaded one), even though everything looks good at runtime and according to the dependency tree.
Why is it doing that? No idea. I've looked at the surefire classpath configuration, and nothing I've tried helps.

Thinking about it now, the only idea I have is to move all tests outside of nd4j-arrow module to some other module that depends on nd4j-arrow. I'll try that and see if it works.

**Comment by raver119** [comment]
What about arrow guys? There were going to fix issue...

**Comment by AlexDBlack** [comment]
Yeah, it's fixed on master as of about a week ago, but we can't access it until 0.11 arrow release.

**Comment by AlexDBlack** [comment]
Last commit here moves tests around (out of nd4j-arrow into nd4j-tests), so should hopefully avoid the test dependency not shaded issue with the tests in nd4j-arrow.

**Comment by AlexDBlack** [comment]
Relocating tests to an entirely different module didn't work.
Looks like the problem is that the maven shade plugin only runs in the package phase, which is after tests, and can't be moved to before the package phase.
And the package phase doesn't run as part of "mvn test" by default (for any modules), hence the original (pre-shade) classes are when running tests instead of the post-shade classes.
Hopefully the last commit (which adds a custom lifecycle) should fix this by forcing the package phase to run for nd4j-flatbuffers even as part of the test phase.

**Comment by AlexDBlack** [comment]
Closing this. Never got this working properly for tests, and arrow 0.11.0 is out now with a fix for the underlying issue.

**Pull request closed without merging**
