### PR TITLE
Fix: Save and Load SequenceVectors

### PR DESCRIPTION
**Pull request by AllenWGX**
## What changes were proposed in this pull request?
Fix Bug : #3348 
              #3326 
## How was this patch tested?
In SequenceVectorsTest example, the testAbstractW2VModel method with adding writing and reading sequence vectors code helps test this PR. But I must point out that since file "big/raw_sentences.txt" described in the example cannot be found, I replace it with the dl4j-example's corresponding file(https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/resources/raw_sentences.txt) and two asserts below are ignored:         
       //assertEquals(242, vocabCache.numWords());
       //assertEquals(634303, vocabCache.totalWordOccurrences());
And then the unit tests can run successfully.

### CODE REVIEW

**Comment by agibsonccc** [comment]
@AllenWGX did you clone and install https://github.com/deeplearning4j/dl4j-test-resources ?

**Comment by AllenWGX** [comment]
@agibsonccc no，I just ran that example with FileNotFoundException and replace the file. Do I need to install the test-resouces and re-test the PR ?

**Comment by agibsonccc** [comment]
Please and thanks! For running dl4j tests you have to use test resources.

**Comment by AllenWGX** [comment]
@agibsonccc Follow your advice, I install the test-sources jar and re-test the code. The log is:  [https://gist.github.com/AllenWGX/61b060d7737548d2d0a01b40114b9865](url). Please see it.

**Comment by agibsonccc** [comment]
@AllenWGX So this looks fixed? Can I close this?

**Comment by AllenWGX** [comment]
@agibsonccc @raver119 the model serialization fixed but there still exists problem in de-serialization. I clone the latest code and test. The log shows : https://gist.github.com/AllenWGX/90bd2002a64389c93f9c49659d485fd1[](url). And I think this PR fix the de-serialization problems which exist in reading empty line and InMemoryLookupTable initialization needs VocabCache besides serialization problem.

**Comment by raver119** [comment]
@AllenWGX is this PR ready for review and merge?

**Comment by AllenWGX** [comment]
@raver119 yeah, I think so. I've tested this PR with dl4j-test-resources already.

**Comment by raver119** [comment]
Great. Looks good to me, merging.

**Pull request merged**
