### PR TITLE
Split tests into smaller files to speed up compilation

### PR DESCRIPTION
**Pull request by yquemener**
On slow compilers DeclarableOpsTests1.cpp, DeclarableOpsTests2.cpp, DeclarableOpsTests7.cpp and DeclarableOpsTests8.cpp can take several minutes to compile. Splitting them in smaller parts allow to parallelize the compilation more efficiently.

### CODE REVIEW

**Comment by saudet** [comment]
@raver119 Are we going to merge this?

**Comment by raver119** [comment]
Sure, why not? There's couple of conflicts though

**Comment by saudet** [comment]
@yquemener The test files have changed a lot, this will need to be redone... :(

**Comment by yquemener** [comment]
Ok, let's just forget about it for now then. I'll just redo it when we stumble on a slow compiler again.

**Pull request closed without merging**
