### PR TITLE
Adding kotlin extension for basic operators

### PR DESCRIPTION
**Pull request by fbrunacci**
Signed-off-by: fbrunacci <fbrunacci@gmail.com>

## What changes were proposed in this pull request?
Adding kotlin extension functions on basic operations to make symbolic representation (like + or *) available.

## How was this patch tested?
unit tests:
nd4k/src/test/kotlin/org/nd4k/INDArrayExtTest.kt

### CODE REVIEW

**Comment by treo** [comment]
I'm against doing it this way. If we want to support the syntactic sugar for Kotlin, those few functions should be added directly on INDArray and SDVariable.

Overall however, I'm not sure if the syntactic sugar is worth the inconsistency across languages. It will create additional confusion for the benefit of being able to use `+,-, /, *` instead of `add, sub, div, mul`, and if you want to use the inplace versions to improve the performance of the implementation where possible you now get a weird usage mix of syntactically sugared and unsugared methods.

**Comment by raver119** [comment]
For Scala we offer those though

With best regards,
raver119
12 мая 2020 г., 22:57 +0300, Paul Dubs <notifications@github.com>, писал:

**Comment by fbrunacci** [comment]
I proposed this pull request because I am currently writing notebooks (jupyter / kotlin) and I needed to make the code more readable. (for presentations / courses)
In one of my kotlin notebooks (inspired by a python notebook), it allowed me to pass from this code
```
// forward
val layer_1 = layer_0.mmul(weights_0_1)
val layer_2 = sigmoid(layer_1.mmul(weights_1_2))

// back propagation
val layer_2_error = layer_2.sub(getTargetForLabel(label))
val layer_2_delta = layer_2_error.mul(sigmoidDerivative(layer_2))

val layer_1_error = layer_2_delta.mmul(weights_1_2.transpose())
// layer_1_delta = layer_1_error

val diff_1_2 = layer_1.transpose().mmul(layer_2_delta)
weights_1_2.subi(diff_1_2.mul(learning_rate))
val diff_0_1 = layer_0.transpose().mmul(layer_1_error)
weights_0_1.subi(diff_0_1.mul(learning_rate))
```
to this code 
```
import org.nd4k.*

// forward
val layer_1 = layer_0.dot(weights_0_1)
val layer_2 = sigmoid(layer_1.dot(weights_1_2))

// back propagation
val layer_2_error = layer_2 - getTargetForLabel(label)
val layer_2_delta = layer_2_error * sigmoidDerivative(layer_2)

val layer_1_error = layer_2_delta.dot(weights_1_2.T())
val layer_1_delta = layer_1_error

weights_1_2 -= layer_1.T().dot(layer_2_delta) * learning_rate
weights_0_1 -= layer_0.T().dot(layer_1_delta) * learning_rate
```
and here is the same portion of code in python / numpy (they also offer this sugar)
```
# forward 
layer_1 = self.layer_0.dot(self.weights_0_1)
layer_2 = self.sigmoid(layer_1.dot(self.weights_1_2))

# Output layer
layer_2_error = layer_2 - self.get_target_for_label(label) 
layer_2_delta = layer_2_error * self.sigmoid_output_2_derivative(layer_2)

layer_1_error = layer_2_delta.dot(self.weights_1_2.T)
layer_1_delta = layer_1_error

self.weights_1_2 -= layer_1.T.dot(layer_2_delta) * self.learning_rate 
self.weights_0_1 -= self.layer_0.T.dot(layer_1_delta) * self.learning_rate 
```

Moreover, the fact of making this available by a kotlin extension in a maven module, allows you to choose whether or not to use it (by adding dependence and import of org.nd4k.*) and allows the user to choose whether he wishes to use this sugar or no.
Which seems less possible if we integrate it directly into INDArray.

**Comment by raver119** [comment]
Yep, we also do that in C++.

**Comment by agibsonccc** [comment]
@fbricon overall looks good as a start. Can you add +=,-=,.. for the inplace operators (anything with an i at the end)?

**Comment by fbricon** [comment]
@agibsonccc you got the wrong @fbrunacci :-)

**Comment by fbrunacci** [comment]
> @fbricon overall looks good as a start. Can you add +=,-=,.. for the inplace operators (anything with an i at the end)?

@agibsonccc Inplace operators are already define because arithmetic operators are used by kotlin to generate augmented assignments. 
https://kotlinlang.org/docs/reference/operator-overloading.html#assignments

I have already used some of them in my projects. (example here: https://github.com/fbrunacci/kotlin-notebook-samples/blob/1a8a4ead8c5d0706291ab0e011958f6eb22a10ba/notebooks/deeplearning4j/SentimentClassificationDemo.ipynb )

**Comment by agibsonccc** [comment]
Closing this. We're not going to add any jvm lang specific modules in the mainline project due to maintenance cost increase. (We recently retried all of our scala syntax enhancements) I'll be happy to put something like this  in our new contrib folder.

**Pull request closed without merging**
