### PR TITLE
Issue #1836

### PR DESCRIPTION
**Pull request by NaturalFractals**
Implemented method to check equality of MultiLayerUpdater. Equality Test in ModelSerializerTest passing.

### CODE REVIEW

**Comment by NaturalFractals** [comment]
Added an extra check in there to be sure both of the Updater arrays were of some length to avoid any type of ArrayOutOfBoundsException.

**Comment by agibsonccc** [comment]
Fix up the indentations a bit and add a cast for the MultiLayerUpdater as another variable. Extra parens everywhere is sloppier :(

**Comment by nyghtowl** [comment]
And we appreciate the help

**Comment by agibsonccc** [comment]
Thanks! Merged.

**Comment by NaturalFractals** [comment]
Thanks for your patience and feedback! I am happy to help!

**Comment by NaturalFractals** [comment]
Also thanks for allowing me to help, you guys are doing some amazing work. And the fact that you are willing to share it with everyone just makes it that much better :)

**Pull request merged**
