### PR TITLE
Workspaces integration

### PR DESCRIPTION
**Pull request by raver119**
***WIP; DO NOT MERGE;***

Integration of Nd4j Workspaces into DL4j NN architectures

Additionally:
- ParallelInference
- minor fixes across code base

### CODE REVIEW

**Comment by crockpotveggies** [comment]
Gave this a test run with Inception, OOMs unfortunately:
https://gist.github.com/crockpotveggies/f12804c6844a03ad1289423d6b5ea907

Am I doing anything wrong with this init?
```
    // set up optimizations
    CudaEnvironment.getInstance().getConfiguration()
            // key option enabled
            .allowMultiGPU(true)
            .allowCrossDeviceAccess(true)
            // we're allowing larger memory caches
            .setMaximumDeviceCache(deviceCache * 1024L * 1024L * 1024L)
            .setMaximumHostCache(12L * 1024L * 1024L * 1024L);
//            .setNumberOfGcThreads(5)
//            .setNoGcWindowMs(gcWindow);

    System.out.println("Available devices: "+CudaEnvironment.getInstance().getConfiguration().getAvailableDevices());

    Nd4j.getMemoryManager().togglePeriodicGc(false);
```

**Comment by raver119** [comment]
Yes,  lots of stuff is wrong.

**Comment by huitseeker** [comment]
rebased here https://github.com/huitseeker/deeplearning4j/tree/deeplearning4j-r119_pages

**Comment by raver119** [comment]
And what should i do now?

**Comment by huitseeker** [comment]
If you like the PR, I can push it to your branch for you. Or you can do the same in the following way:

```bash
cd /path/to/checkout/of/deeplearning4j
git remote add huitseeker git://github.com/huitseeker/deeplearning4j
git remote update
git checkout r119_pages
git reset --hard huitseeker/deeplearning4j-r119_pages
git push -f origin # assuming origin is the name of your remote for github.com/deeplearning4j, gitremote -v to check
```

**Pull request merged**
