### PR TITLE
Fix keras model importing bug when tensorflow scope used

### PR DESCRIPTION
**Pull request by zheolong**
## What changes were proposed in this pull request?

fix issues/3597, the keras model loading bug, when tensorflow scope used 

My method is parsing the 'nested' group structure from h5 or weight file like below.

default

## How was this patch tested?

unit test, test cases:

1. loading single h5 file without tensorflow scope
2. loading weight file and json file without tensorflow scope
3. loading single h5 file with tensorflow scope
4. loading weight file and json file with tensorflow scope

[model_files_for_test.tar.gz](https://github.com/deeplearning4j/deeplearning4j/files/1217845/model_files_for_test.tar.gz)

### CODE REVIEW

**Comment by agibsonccc** [comment]
@zheolong can you add a test (even if it's just your model?) to the unit tests under modelimport?

**Comment by zheolong** [comment]
@agibsonccc ok, I will and unit tests

**Comment by zheolong** [comment]
@agibsonccc How can I put keras model files under this url, ```http://blob.deeplearning4j.org/models/```, or just put them under resources dir of project

**Comment by agibsonccc** [comment]
@zheolong just put them under resources. Thanks!

**Comment by zheolong** [comment]
@agibsonccc unit test added, you can compile the whole project and check it

**Comment by zheolong** [comment]
@agibsonccc done

**Comment by agibsonccc** [comment]
I don't have anything more to say. I'll let @maxpumperla comment on the rest.

**Comment by zheolong** [comment]
@agibsonccc cool

**Comment by maxpumperla** [comment]
@zheolong Thanks for your contribution.

Sorry, I should have reviewed earlier, but I'm afraid this PR broke one of the tests, namely https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/test/java/org/deeplearning4j/nn/modelimport/keras/KerasCustomLayerTest.java

```
org.deeplearning4j.nn.modelimport.keras.InvalidKerasConfigurationException: Error when attempting to copy weights from Keras layer conv1/7x7_s2 to DL4J layer conv1/7x7_s2(weights is null). For more information, see http://deeplearning4j.org/model-import-keras.
```

Would you please consider having a look? Thanks

**Comment by maxpumperla** [comment]
@zheolong I'm struggling a bit to get this straight, we might have to revert... would be a pity.

In your unit test, I see how it makes sense to find the nested groups:
```
Name: 
dense_1/xxx/yyy
Fragments: 
[dense_1, xxx, yyy]
Fragments[0]: 
dense_1
attributeJoinStr: 
global/shared/dense_1/xxx
```

In the above-mentioned unit test, it conflates weights that should remain separate (hence the `weights` are empty and we can't load the layer):
```
Name: 
conv1/7x7_s2
Fragments: 
[conv1, 7x7_s2]
Fragments[0]: 
conv1
attributeJoinStr: 
conv1/7x7_s2_Wconv1/7x7_s2_b
```

would be great to get your feedback here, since you did all the good work.

**Comment by maxpumperla** [comment]
Little update: it seems this `conv1/7x7_s2_Wconv1/7x7_s2_b` _is_ the `weight_names` attribute of that layer, hence it's set to `attributeJoinStr`. The actual weight names only come after, see cryptic hdf5 snippet below.

```
weight_names conv1/7x7_s2_Wconv1/7x7_s2_bH@@   ���}YH���TREE�������������������y�PB财x�j$x��P(
�8HEAPX(8�7x7_s2_W7x7_s2_b
```

**Comment by zheolong** [comment]
@maxpumperla let me check this

**Comment by zheolong** [comment]
@maxpumperla check this new pull request #3860

**Comment by zheolong** [comment]
@maxpumperla check this, please. #3861

**Pull request merged**
