### PR TITLE
ND4J: Fix build for linux-arm64

### LINKED ISSUE #7687: building nd4j fails on jetson nano board arm64 armv8-a
#### Issue Description

I recently started trying to build deeplearning4j on the Jetson Nano board.  I was able to compile libnd4j, however when i then try to go and build nd4j, it fails due to missing dependencies for  "mkl-dnn"  ..  

So, I began building mkl-dnn from javacpp-presets natively on the jetson nano, unfortuantely this fails because mkl-dnn depends on x86 specific included header files  ( cpuid.h for example that is not available on the arm platform.)

so..  The questions is, should i skip trying to do the native builds and only do the cuda builds for that platform?   I tried this by removing the references to nd4j-native / nd4j-native-platform backend impls, ..  the build got further, however then crashed in nd4j-grpc  due to another dependency on dnn-mkl.  

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for nd4j 1.0.0-beta3:
[INFO]
[INFO] nd4j ............................................... SUCCESS [  9.094 s]
[INFO] nd4j-shade ......................................... SUCCESS [  0.674 s]
[INFO] jackson ............................................ SUCCESS [ 53.685 s]
[INFO] nd4j-common ........................................ SUCCESS [ 18.707 s]
[INFO] nd4j-context ....................................... SUCCESS [  3.935 s]
[INFO] nd4j-buffer ........................................ SUCCESS [  6.378 s]
[INFO] nd4j-backends ...................................... SUCCESS [  0.414 s]
[INFO] nd4j-api-parent .................................... SUCCESS [  0.469 s]
[INFO] nd4j-api ........................................... SUCCESS [03:30 min]
[INFO] nd4j-jdbc .......................................... SUCCESS [  0.396 s]
[INFO] nd4j-jdbc-api ...................................... SUCCESS [  3.456 s]
[INFO] nd4j-jdbc-mysql .................................... SUCCESS [  3.521 s]
[INFO] nd4j-jdbc-hsql ..................................... SUCCESS [  4.002 s]
[INFO] nd4j-instrumentation ............................... SUCCESS [  4.652 s]
[INFO] nd4j-serde ......................................... SUCCESS [  0.299 s]
[INFO] nd4j-aeron ......................................... SUCCESS [  6.922 s]
[INFO] nd4j-base64 ........................................ SUCCESS [  2.952 s]
[INFO] nd4j-jackson ....................................... SUCCESS [  3.695 s]
[INFO] nd4j-kryo .......................................... SUCCESS [  6.883 s]
[INFO] nd4j-camel-routes .................................. SUCCESS [  0.282 s]
[INFO] nd4j-kafka ......................................... SUCCESS [  3.437 s]
[INFO] nd4j-gson .......................................... SUCCESS [  3.111 s]
[INFO] nd4j-arrow ......................................... SUCCESS [  3.499 s]
[INFO] nd4j-grpc .......................................... FAILURE [01:13 min]
[INFO] nd4j-native-api .................................... SKIPPED
[INFO] nd4j-tests ......................................... SKIPPED
[INFO] nd4j-backend-impls ................................. SKIPPED
[INFO] nd4j-cuda .......................................... SKIPPED
[INFO] nd4j-cuda-platform ................................. SKIPPED
[INFO] nd4j-tensorflow .................................... SKIPPED
[INFO] nd4j-tests-tensorflow .............................. SKIPPED
[INFO] nd4j-parameter-server-parent ....................... SKIPPED
[INFO] nd4j-parameter-server-model ........................ SKIPPED
[INFO] nd4j-parameter-server .............................. SKIPPED
[INFO] nd4j-parameter-server-status ....................... SKIPPED
[INFO] nd4j-parameter-server-client ....................... SKIPPED
[INFO] nd4j-parameter-server-rocksdb-storage .............. SKIPPED
[INFO] nd4j-parameter-server-node ......................... SKIPPED
[INFO] nd4j-uberjar ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:07 min
[INFO] Finished at: 2019-05-07T23:54:12-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project nd4j-grpc: Could not resolve dependencies for project org.nd4j:nd4j-grpc:jar:1.0.0-beta3: The following artifacts could not be resolved: org.nd4j:nd4j-native:jar:linux-arm64:1.0.0-beta3, org.bytedeco.javacpp-presets:mkl:jar:linux-arm64:2019.0-1.4.3, org.bytedeco.javacpp-presets:mkl-dnn:jar:linux-arm64:0.16-1.4.3: Could not find artifact org.nd4j:nd4j-native:jar:linux-arm64:1.0.0-beta3 in maven-restlet (http://maven.restlet.org) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
```

### PR DESCRIPTION
**Pull request by saudet**
Fixes #7687

## What changes were proposed in this pull request?

Add missing profile to pom.xml file for build to succeed on linux-arm64

## How was this patch tested?

Untested on linux-arm64, but build still passes on other platforms

@kwatters Could you try with `mvn clean install -Dmaven.test.skip -Djavacpp.platform=linux-arm64`?

### CODE REVIEW

**Comment by AlexDBlack** [comment]
@saudet I had intended to test this, but I'm running into build issues (this is compiling directly on my Jetson Nano - using the Ubuntu 18.04 image from here: https://developer.nvidia.com/embedded/downloads )

https://gist.github.com/AlexDBlack/0b9525be3d8d84fd612fa6cbf2bd9d63

cc @kwatters - have you documented your build process?

**Comment by saudet** [comment]
Looks like we need to update buildnativeoperations.sh, should work now.

**Comment by AlexDBlack** [comment]
@saudet Thanks, it's building now. Will post result for nd4j once it gets there...

**Comment by saudet** [comment]
We'll also need to build at least OpenBLAS but I'm waiting for a PR from @kwatters for this to work.

**Comment by kwatters** [comment]
You guys rock.  Thanks for helping out,  it's slow going building on the Nano.  There are a few small changes to the cppbuild.sh file just to add the "linux-arm64"  platform.  For now, i'm building natively on the nano, so it was sufficient for me to just specify   gcc / g++ / gfortran  as the compilers.  (I could update this with "aarch64-linux-gnu-gcc-7"  .. etc..

That would be a PR for JavaCPP-Presets ...  I have forked it..  I assume you want it on master?

One comment about building OpenBLAS on the Jetson Nano.  It ran out of memory a few times when I was trying to build it.  It seemed random.  So,  while building OpenBLAS,  I ensured I didn't have any other programs running ...  The second thing I did which was the trick was to add some swap space.  I know this isn't a good thing for an SD card, but it was the difference between being able to compile or not.

I added a 4GB swap space, that seemed to be sufficient.
as Root: 
```
dd if=/dev/zero of=/swapfile bs=4096 count=1048576   
mkswap /swapfile
swapon -a  /swapfile
```

**Comment by kwatters** [comment]
I have the openblas jar file built on the nano, do you want me to post /attach it here?  The next problem I ran into building nd4j was in the nd4j native backend.  that relies on mkl and mkl-dnn.  

Interestingly (and not surprising)  the Nano comes pre-installed with Cuda 10.0 

From:  https://smist08.wordpress.com/2019/04/03/playing-with-cuda-on-my-nvidia-jetson-nano/
```
export PATH=${PATH}:/usr/local/cuda/bin
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda/lib64
```

Once your path(s) are setup, you can run  "nvcc"  which I guess is the cuda specific compiler?   I think it'd be ok to skip the nd4j native builds for this platform, and just focus on the cuda 10 build..  (maybe side-step the mkl / mkl-dnn dependency problem.)

**Comment by saudet** [comment]
@kwatters Have you tried to build from this branch with explicit `-Djavacpp.platform=linux-arm64`?

**Comment by AlexDBlack** [comment]
This is as far as I got with the build usind -Djavacpp.platform=linux-arm64:
https://gist.github.com/AlexDBlack/9763708e2c3cdca07dea1d8f658919c6

**Comment by kwatters** [comment]
@saudet   I did, sorry I haven't been reporting all of my progress.  anyway.  few things to update.

1. yes.  I did explicitly specify linux-arm64  (and that seems to clear up confusion in the artifacts between aarch64 and arm64 being generated.

```
mvn clean install -Dmaven.javadoc.skip=true -DskipTests -Djavacpp.platform=linux.arm64
```

This still leaves me with the native-platform 

2. @AlexDBlack   I was able to successfully build the openblas arm64 jar locally from javacpp-presets.  (just make sure you have some swap space allocated.. )  I can resolve this jar from my local maven cache..  I'm happy to send my locally built jar to you for testing if you like.

Once the openblas stuff is resolved, you will hit the issue with nd4j-native-platform requiring  mkl and mkl-dnn  ..  

On a side note,  I was able to build libnd4j with the cuda bindings..  (it took overnight to finish building..)

I was successful after setting the PATH/ LD_LIBRARY_PATH as mentioned above.. the following command seemed to be successful:

```
./buildnativeoperations.sh -platform=linux-arm64 -c cuda -cc 53
```
The Jetson Nano is listed as compatibility version "5.3" 

  the last line of the build said  "100% Built target nd4jcuda"   so ..  I think that's good.. :)


3

**Comment by saudet** [comment]
> Once the openblas stuff is resolved, you will hit the issue with nd4j-native-platform requiring mkl and mkl-dnn ..

This is what this PR is for. I don't see mkl-dnn anywhere in the dependencies:

> $ cd nd4j/nd4j-backends/nd4j-backend-impls
> $ mvn -N clean install -Dmaven.test.skip
> $ cd nd4j-native-platform
> $ mvn clean install -Djavacpp.platform=linux-arm64
> [ERROR] Failed to execute goal on project nd4j-native-platform: Could not resolve dependencies for project org.nd4j:nd4j-native-platform:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.nd4j:nd4j-native:jar:linux-arm64:1.0.0-SNAPSHOT, org.bytedeco:openblas:jar:linux-arm64:0.3.5-1.5: Failure to find org.nd4j:nd4j-native:jar:linux-arm64:1.0.0-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

What do you get?

**Comment by AlexDBlack** [comment]
I can confirm that after building openblas for linux-arm64 using javacpp-presets (1.5 tag + slight modification to build script), the ND4J build completes successfully for CPU on the Jetson Nano (on this branch/PR).
I haven't tried CUDA yet, or actually doing anything with the build. I'll get to that later :)

@kwatters Thanks for the suggestions above, especially the swap file.

**Comment by AlexDBlack** [comment]
Unfortunately my build attempt with CUDA was not successful...
https://gist.github.com/AlexDBlack/25f7399cee02872bc90396f0be4d0ffe

**Comment by kwatters** [comment]
@AlexDBlack  Ah. yes. I forgot about that. I did have to make a small change to the flags being passed..  
As you probably saw here:
```
cc: note: valid arguments to ‘-mcmodel=’ are: large small tiny
```

The default build specifies a value of "medium" here which isn't valid...   I have no idea what a proper value to use for the nano is, so I updated the  

libnd4j/blas/CMakeLists.txt file to update the flag for -mcmodel=small

After doing that.. and waiting like 10 hours for a build to complete..  It appeared to be successful.  (I'm not sure if i should have specified large, small, or tiny..  )

@saudet   I am probably getting myself confused as to the error messages that I'm seeing now.  I started this journey by trying to build for 1.0.0-beta3.. then to 1.0.0-beta4 ..   I suppose I should be looking at master for both javacpp and for deeplearning4j?

**Comment by kwatters** [comment]
ah,  so more updated..  the "mkl" / "mkl-dnn" dependencies I was actually hitting when building MyRobotLab, because those are defined as transient dependencies for nd4j-native in the pom

https://mvnrepository.com/artifact/org.nd4j/nd4j-native/1.0.0-beta4

For now,  I'll exclude those modules and see if that breaks my myrobotlab build...    I'll post with anything else that I find out today as I continue working through building the various dependencies.

**Comment by saudet** [comment]
@raver119 Why is mcmodel specified in libnd4j/blas/CMakeLists.txt?

**Comment by kwatters** [comment]
Good news.. I seem to have been able to build nd4j native on the Jetson nano ... No idea of it works yet, but I did want to report back on my success.

**Comment by saudet** [comment]
I've removed `-mcmodel=medium` and it still works fine on my machine (Fedora 30, GCC 9.1, CUDA 10.1).
If that's working alright for everyone, we'll merge it like that. @raver119

@sshepel Do we have a way to run the CUDA tests for Linux on the CI server?

**Comment by sshepel** [comment]
@saudet yep, we do...

**Comment by raver119** [comment]
Confirmed to work for both default and experimental mode.

**Comment by AlexDBlack** [comment]
Changes look fine, but here's what I'm seeing when I try CUDA build now:
https://gist.github.com/AlexDBlack/6f10ff4c996ca9445104aa3fbcc598e2

**Comment by saudet** [comment]
@AlexDBlack Make sure to specify the platform explicitly with `-Djavacpp.platform=linux-arm64`

**Comment by AlexDBlack** [comment]
The failure is in buildnativeoperations.sh script, I'm not using Maven (so -D won't be used here?).
The exact build command (also in the gist)
`./buildnativeoperations.sh -platform=linux-arm64 -c cuda -cc 53`

**Comment by saudet** [comment]
The script isn't parsing with an "=" sign in that case.

**Comment by AlexDBlack** [comment]
Ah, derp. Yep, builds now with `./buildnativeoperations.sh -platform linux-arm64 -c cuda -cc 53`
It hasn't finished, but no problems so far...

Given the build works for @kwatters I guess we go ahead and merge...

**Pull request merged**
