### PR TITLE
Nd4j versioning change ADR

### PR DESCRIPTION
**Pull request by agibsonccc**
## What changes were proposed in this pull request?
ADR for version change allowing helpers to be introduced as optional enhancements for users on different platforms.
These helpers include components like armcompute, onednn, cudnn

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [X ] Created tests for any significant new code additions.
- [ X] Relevant tests for your changes are passing.

### CODE REVIEW

**Comment by saudet** [comment]
I'm not sure I understand how that's better than JavaCPP extensions. We
only need to set javacpp.platform anyway with the way things are right now.

**Comment by agibsonccc** [comment]
@saudet  FWIW this is why it's an ADR :) the point is to discuss the trade offs before writing code. For now, I want to flesh out a better way of handling the javacpp.platform standardization. A big (at least perceived, correct me if I'm wrong) issue is when working with javacpp.platform to reduce the number of dependencies works well, but is kind of an edge case when you blend something with extensions with something that doesn't. The goal is to make it a bit easier for people to use 1 workflow.
I like the way the presets does it where it shows the software being provided + the javacpp version that the bindings were done with. I figured piggybacking the extension on that made a bit of sense.

**Comment by saudet** [comment]
I'm not aware of any "edge case" w.r.t to extensions. You'll need to explain what you're referring to.

**Comment by agibsonccc** [comment]
@saudet  sure I'll be excited if this is a mis understanding. When we specify -Djavacpp.platform=windows-x86_64, does this exclude the classifiers with avx? Say: windows-x86_64-avx or something similar. If we  want to only include dependencies for windows, but also include anything that might optionally be windows avx, is that possible or does it have to be both? The main concern is uniformly being able to bundle the dependencies for platforms you want while also allowing the extensions you want. It seems like it might be difficult to specify both. (FWIW, I'll update the ADR with the discussion notes here so we can file this away under the docs and record the decision as well)

**Comment by saudet** [comment]
Yes, that works just fine. Like I said, that's how it works right now, or actually we'd have to add nd4j-native-platform-avx/pom.xml, etc files that looks like the ones for GPU and MKL in the case of TF Java here: 
https://github.com/tensorflow/java/tree/master/tensorflow-core

**Comment by agibsonccc** [comment]
Ok then I'll update the ADR to use extensions then. Thanks!

**Comment by agibsonccc** [comment]
@saudet  updated the ADR to use extensions.

**Review by saudet — DISMISSED** [review]
The decision hasn't been updated and there are unrelated changes in the PR, but if that's alright with you, feel free to merge.

**Comment by agibsonccc** [comment]
@saudet  I updated the decision to accepted. Regarding the decision, it was updated to use extensions instead of the version. I clarified my wording there to make sure that was more explicit. Thanks for highlighting that.

**Review by saudet — APPROVED** [review]
There's still some unrelated changes, but looks harmless enough.

**Comment by agibsonccc** [comment]
@saudet  ah yeah, that's related to another PR. Intellij has been doing some auto spacing/indent. That will be cleaned up in another PR. Thanks!

**Pull request merged**
