### PR TITLE
Automated syntax correction and enforcement

### PR DESCRIPTION
**Pull request by huitseeker**
Please refer to https://github.com/deeplearning4j/nd4j/pull/ this is the same idea applied to a different repo.
Enforces https://google.github.io/styleguide/javaguide.html

I'll just repeat how you can get automated formatting in case of an issue:
- run 'mvn formatter:format' in any subproject you want
- use the IDEA plugin https://plugins.jetbrains.com/idea/plugin/8527-google-java-format
- use Eclipse's built-in code formatter with the provided contrib/formatter.xml format file
- if all else fails, replace in the root pom the goal of the mvn-formatter-plugin :
  <goal>validate</goal>
  with
  <goal>format</goal>

### CODE REVIEW

**Comment by huitseeker** [comment]
I can remove the enforcement for now, if need be.

**Comment by agibsonccc** [comment]
Could we get rid of the conflicts?

**Comment by agibsonccc** [comment]
Closing this for now. Re open without enforcement and clear up the clashes.

**Comment by huitseeker** [comment]
@agibsonccc Done https://github.com/deeplearning4j/deeplearning4j/pull/2983

**Pull request closed without merging**
