### PR TITLE
libnd4j: Build tests as part of the main build

### LINKED ISSUE #5365: Create build/run script for libnd4j tests
While implementing logic for tests stage in CI pipeline, have been noticed that most of the test parameters for the scripts are not platform specific. Spent several days on debugging this with @raver119.

Ideally we need to have smth like `buildnativeoperations.sh` to build and run tests for specific platform.

### PR DESCRIPTION
**Pull request by saudet**
Fixes #5365, prevents building the source multiple times when running tests.

Tested manually on some architectures of Linux, Mac, Android, iOS, and Windows, and works fine.

### CODE REVIEW

**Comment by raver119** [comment]
Holy shit. I've spent some time today, trying to understand why each my change causes full recompilation :)

I've blamed everything, but CMakeList changes :)

**Comment by sshepel** [comment]
Awesome changes @saudet , that's exactly what we need.

On more question to @raver119 , you mentioned in https://github.com/deeplearning4j/deeplearning4j/issues/5365 that there are some changes for `CMakeLists.txt` in tests that we not merged yet. Will it be easy to merge them after this PR goes to master?

**Comment by raver119** [comment]
No, we shouldn’t wait for CUDA

**Comment by saudet** [comment]
@sshepel Feel free to merge if it's alright with you!

**Comment by saudet** [comment]
@raver119 Your tests are failing when not compiled with "-march=native" and since we can't release binaries with "-march=native", you need to fix this.

@sshepel If you need to stop deploying snapshots until this gets fixed, that's fine, but let's not wait because of that to get this PR merged. This PR doesn't break anything that wasn't already broken. For now, let's just ignore the failing tests, if possible. Thanks!

**Comment by sshepel** [comment]
Ok, @saudet, let me update this branch to the latest master... and than merge.

**Comment by raver119** [comment]
@saudet which tests are failing without march=native? Mind adding some details?

https://github.com/deeplearning4j/deeplearning4j/blob/781bc63058d8f6d73c75b6af4c1b762674126eae/libnd4j/tests_cpu/layers_tests/CMakeLists.txt#L26-L41

We shouldn't run tests with native, unless _RELEASE flag is set.

**Comment by raver119** [comment]
Nevermind, it's reproducible for me as well.

**Comment by raver119** [comment]
Workaround added to current master. But this issue means, that we will need to add release-mode tests for libnd4j as well. 

So, debug tests to ensure nothing leaks.
release x86_64 tests to check for this kind of problems.
release avx2 tests to check for all other possible problems.

**Comment by saudet** [comment]
@raver119 That's what this PR does, it runs the tests in the same mode that the lib for libnd4j gets built with because it actually links with it.

**Comment by saudet** [comment]
@raver119 But now it doesn't build on a bunch platforms :(

**Pull request merged**
