### PR TITLE
Fix string histograms

### PR DESCRIPTION
**Pull request by Foorcee**
## What changes were proposed in this pull request?

Fixes: String analysis wrong histogram calculation #9311

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ x] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ x] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ x] Created tests for any significant new code additions.
- [ x] Relevant tests for your changes are passing.

### CODE REVIEW

**Review by agibsonccc — APPROVED** [review]

**Comment by Foorcee** [comment]
Would it be possible to deploy it as a snapshot?

**Comment by agibsonccc** [comment]
@ForceUpdate1  keep an eye here: https://oss.sonatype.org/content/repositories/snapshots/org/datavec/datavec-api/1.0.0-SNAPSHOT/ for when it's updated. I'll get to it within the next day or so.

**Comment by Foorcee** [comment]
I saw that the dependency was updated, but the changes are not included there?

**Comment by agibsonccc** [comment]
@ForceUpdate1  if it's not just clone the repo as you normally would and mvn clean install just that dependency. I'll  make sure it gets pushed tomorrow.

**Pull request merged**
