### PR TITLE
Added nextRecord to ExcelRecordReader to prevent a bug with hasNext() calls

### PR DESCRIPTION
**Pull request by yquemener**
calling nextRecord on an ExcelRecordReader would call the super() function, which results in returning raw binaries from the file.

### CODE REVIEW

**Comment by yquemener** [comment]
The tests failed even before that modification because a file named datavec-excel/testsheet.xlsx is nowhere to be found in the repository. That may be another thing to repair.

**Comment by AlexDBlack** [comment]
@yquemener All datavec tests are passing (at least last time I checked - last weekd), and have been for a while...
The test resources you are referring to is here: https://github.com/deeplearning4j/dl4j-test-resources/tree/master/src/main/resources/datavec-excel
Just make sure you have dl4j-test-resources installed, and have the appropriate profile enabled (test-nd4j-native)

**Comment by yquemener** [comment]
Thanks, the tests now run and show an error! Correcting it now.

**Comment by AlexDBlack** [comment]
@yquemener can this be merged now?

**Comment by yquemener** [comment]
Yes, thanks!

**Comment by yquemener** [comment]
This one would be useful to Discover too: https://github.com/deeplearning4j/deeplearning4j/pull/5782

**Pull request merged**
