### PR TITLE
Added DataSetF1Calculator

### PR DESCRIPTION
**Pull request by marcel-93**

### CODE REVIEW

**Comment by agibsonccc** [comment]
Mind adding some tests now?

**Comment by marcel-93** [comment]
not sure what i should test here

**Comment by agibsonccc** [comment]
Mainly example usage helps

**Comment by agibsonccc** [comment]
Any updates here?

**Comment by marcel-93** [comment]
sry at the moment i dont have the time to work on this

**Comment by huitseeker** [comment]
This PR is fairly old and there hasn't been much activity on it. Closing, but please re-open if you find time to shape it up.

**Pull request closed without merging**
