### PR TITLE
Spark ML (experimental)

### PR DESCRIPTION
**Pull request by EronWright**

### CODE REVIEW

**Comment by EronWright** [comment]
I am unable to build a MultiLayerConfiguration with an output layer - I suspect that the JSON serialization round-trip is lossy.  Any suggestions before I dig deeper?

Given the configuration seen in the JavaIrisClassificationPipeline example program, I get:

```
17:27:43,696 INFO  ~ Training on layer 1 with 89 examples
17:27:43,696 INFO  ~ Training on layer 1 with 92 examples
17:27:43,717 WARN  ~ Output layer not instance of output layer returning.
17:27:43,727 WARN  ~ Output layer not instance of output layer returning.
17:27:43,736 INFO  ~ Training on layer 1 with 92 examples
17:27:43,737 INFO  ~ Training on layer 1 with 89 examples
17:27:43,762 WARN  ~ Output layer not instance of output layer returning.
17:27:43,780 WARN  ~ Output layer not instance of output layer returning.
...
java.lang.ClassCastException: org.deeplearning4j.models.featuredetectors.rbm.RBM cannot be cast to org.deeplearning4j.nn.layers.OutputLayer
	at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.labelProbabilities(MultiLayerNetwork.java:1078)
	at org.apache.spark.ml.classification.NeuralNetworkClassificationModel.predictProbabilities(MultiLayerNetworkClassification.scala:138)
```

**Comment by agibsonccc** [comment]
Do you pass in a multi layer configuration at all? Show me an example.

**Comment by EronWright** [comment]
The configuration is here: [JavaIrisClassificationPipeline#L88](https://github.com/EronWright/spark-examples/blob/feature-spark-ml/src/main/java/org/deeplearning4j/ml/JavaIrisClassificationPipeline.java#L88).  The code was copied from [TestSparkMultiLayer#L151](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/spark/dl4j-spark/src/test/java/org/deeplearning4j/spark/impl/multilayer/TestSparkMultiLayer.java#L151), which likewise uses the IRIS dataset.   I tried a few variants to no avail.

**Comment by EronWright** [comment]
Note that many unit tests (including org.deeplearning4j.nn.conf.MultiLayerNeuralNetConfigurationTest) fail on my machine (which is OSX/Java8).  The issue is obviously unrelated to this PR and I will submit a new PR for the issue.

**Comment by EronWright** [comment]
Updated PR with latest changes.

**Comment by EronWright** [comment]
Closing this PR.   The code is being ported to Spark 1.4 and decoupled from the dl4j-spark module.

**Pull request closed without merging**
