### PR TITLE
Deprecate `GradientPlotterIterationListener` and NeuralNetPlotterIterationListener

### PR DESCRIPTION
**Pull request by Ingwar**
According to the #958, they are not supported anymore.

### CODE REVIEW

**Comment by Ingwar** [comment]
Actually, are others iteration listeners in the `org.deeplearning4j.plot.iterationlistener` still supported or they should be deprecated too?

**Comment by agibsonccc** [comment]
Anything to do with the neuralnetplotter more or less. There's some other
ones in there.

Thanks!

**Comment by Ingwar** [comment]
OK, I'll take a closer looks at them and add suspicious ones to this PR.

**Comment by Ingwar** [comment]
Also, I am wondering, why Travis build have failed? I haven't touched the code of the listeners, so the build shouldn't be affected.

**Comment by AlexDBlack** [comment]
@Ingwar I wouldn't worry about Travis right at the moment. It used to work, but there's some issues with it after CodeHaus shut down that we haven't got around to fixing yet.

**Comment by Ingwar** [comment]
I've marked all other literation listeners that use `NeuralNetPlotter` as well as `NeuralNetPlotter` itself as deprecated.

**Pull request merged**
