### PR TITLE
Support per-example and per-timestep weights

### PR DESCRIPTION
**Pull request by EdeMeijer**
As discussed in https://github.com/deeplearning4j/deeplearning4j/issues/2616, this diff adds support for using arbitrary weights in output masks to enable per-example and per-timestep weights. It really only required a one liner change and implementing it this way guarantees backwards compatibility.

The tests are written using computation graph, but should work with multi layer networks as well since the actual change was in the base layer.

### CODE REVIEW

**Comment by AlexDBlack** [comment]
So it's a good start - but I'm pretty sure there's a few more things we need here.
For example, the evaluation classes assume 0/1 mask values; I'd also want some gradient checks with this.

Perhaps I'll start from this and review those issues - and see if there are any other places that might not work as expected using this approach.

**Comment by EdeMeijer** [comment]
Please do. I think we don't need full support for every conceivable scenario in the first version, but add support as they come. When documenting this feature, we could mention which cases are supported and which aren't. For example 4D probably won't work yet.

I guess evaluation is pretty important to get right immediately. Gradient checks would be nice too. I know about the concept, but haven't implemented my own so far, so I'd rather leave that to you.

**Comment by AlexDBlack** [comment]
Sure, that's fine. I've worked entensively on both, so it shouldn't take me long.
Beyond that, I mainly just want to know where the issues are (and what we need to fix) before declaring to the world that we have this as a feature. :)

**Comment by AlexDBlack** [comment]
@EdeMeijer fyi I do still intent to review and add to this, just haven't had the bandwidth to do it yet. I realize it's been a while.

**Comment by EdeMeijer** [comment]
That's okay, I understand. I'm busy with some non deep learning stuff atm anyway.

**Comment by mbkennel** [comment]
My request is for per-sample weights to work with the ROC performance measurement.

**Comment by agibsonccc** [comment]
Where are we with this?

**Comment by agibsonccc** [comment]
This was a lot more work than we expected to get merged. Closing this for now due to inactivity.

**Pull request closed without merging**
