### PR TITLE
Update GoogLeNet.java

### PR DESCRIPTION
**Pull request by ngujdi**
## What changes were proposed in this pull request?
fix bug

### CODE REVIEW

**Comment by maxpumperla** [comment]
@crockpotveggies would you have time to do a review and merge? Seems to work, but idk the details of naming conventions here.

**Comment by huitseeker** [comment]
Ping @crockpotveggies who's back from PTO.

**Comment by crockpotveggies** [comment]
Right now @raver119 and I are looking at the DL4J implementation since it differs from the pretrained version of it. Appears that it doesn't completely match the model in the paper. So will approve these changes but a quick note that we will probably rewrite this in the immediate future.

**Comment by crockpotveggies** [comment]
@ngujdi unfortunately your PR breaks the master branch. Can you please review it, try to rebuild it locally, and figure out why our build and tests are failing?

**Pull request merged**
