### PR TITLE
The first draft of buildtools.md, canova.md, csv-deep-learning.md, customdata.md created ready to go online.

### PR DESCRIPTION
**Pull request by eiida**
Created.

Please put it online.

### CODE REVIEW

**Comment by eiida** [comment]
Please put the Japanese version of canova.md online.

**Comment by eiida** [comment]
Please put the Japanese version of cv-deep-learning.md online.

**Comment by saudet** [comment]
When there is already a pull request that hasn't been merged, you don't need to create a new one. The other one (pull #4048) gets updated automatically.

**Comment by saudet** [comment]
Corrected a few formatting issues, but looks good, thanks!

**Pull request merged**
