### PR TITLE
add sea temp2

### PR DESCRIPTION
**Pull request by bpark738**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Reviewed the [Contributing Guidelines](https://github.com/deeplearning4j/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.
- [ ] Ran mvn formatter:format (see [formatter instructions](http://code.revelc.net/formatter-maven-plugin/examples.html#Setting_Source_Files) for targeting your specific files).

### CODE REVIEW

**Comment by crockpotveggies** [comment]
SeaTemp looks good, doing the same now with your instacart tutorial.

**Comment by bpark738** [comment]
also added cloud notebook for the blog. 

what's happening here with this pull request?

**Comment by saudet** [comment]
@bpark738 Sorry, we've moved the entire repository in the "deeplearning4j" subdirectory, so we'll need to update the PR accordingly.

@crockpotveggies Are you happy with the changes though?

**Comment by eraly** [comment]
@bpark738 We recently removed support for GravesLSTM so switch to LSTM.Builder()

**Comment by crockpotveggies** [comment]
@eraly I think Briton is off for the summer and won't respond for a few
months. Can you pick this up?

**Comment by eraly** [comment]
Sure. How about we merge this now so Briton gets his github credits and I'll open a separate pr with the change?

**Comment by AlexDBlack** [comment]
@eraly FYI alternatively you can also start from his branch (follow step 1 under "command line instructions" here)
```
git checkout -b <new_branch_name> master
git pull https://github.com/bpark738/deeplearning4j.git master
```
He'll still get credit, but you can add more commits before merging.

**Comment by eraly** [comment]
Thanks @AlexDBlack. 

@crockpotveggies Briton says he'll make the changes.

**Comment by bpark738** [comment]
updated graveslstm to lstm

**Comment by eraly** [comment]
Thanks Briton.

**Pull request closed without merging**
