### PR TITLE
Implement Product in doForward() & doBackward() in ElementWiseVertex.java

### PR DESCRIPTION
**Pull request by Oscarlight**
Hi, Alex,

I have implemented Product operation in doForward() & doBackward() in ElementWiseVertex.java. I have tested in my experiment and it seems work fine. Please let me know if you see any change required. Thank you for your constant support for us in the Github!!

Best,
Mingda

### CODE REVIEW

**Comment by AlexDBlack** [comment]
Great, thanks.

2 things we'll need to do here:

1. Can you make sure it's up to date (I'm seeing merge conflicts that need to be resolved first)
2. Add Op.Product to this gradient check: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/gradientcheck/GradientCheckTestsComputationGraph.java#L146

We'll need to make sure the gradient check passes before we can merge this.

**Comment by huitseeker** [comment]
Hi @Oscarlight, and thanks for the nice PR. Any news on the changes @AlexDBlack suggested ?

**Comment by Oscarlight** [comment]
Thanks for following up! Francois. Sorry for the delay. I just got back
from traveling and will make the changes this weekend :)

On Feb 10, 2017 09:21, "François Garillot" <notifications@github.com> wrote:

Hi @Oscarlight <https://github.com/Oscarlight>, and thanks for the nice PR.
Any news on the changes @AlexDBlack <https://github.com/AlexDBlack>
suggested ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/deeplearning4j/deeplearning4j/pull/2751#issuecomment-278952929>,
or mute the thread

**Comment by AlexDBlack** [comment]
@Oscarlight apologies, I missed your comment here. Feel free to message me directly on gitter if you don't hear back within say 24 hours on github.

Re: running tests, you'll need to use the maven profile to specify a backend. Usually just append "-P test-nd4j-native" to your "mvn" commands.

https://github.com/deeplearning4j/deeplearning4j/blob/master/pom.xml#L129

**Comment by Oscarlight** [comment]
Thank you! Alex. Will do that tomorrow.

Best,
Mingda

**Comment by agibsonccc** [comment]
Closing due to inactivity.

**Pull request closed without merging**
