### PR TITLE
Fix #9332

### LINKED ISSUE #9332: 1.0.0-M1 wrong CUDA malloc()
* When allocating by 2 mb or less here is a low memory allocation efficiency. NVIDIA GeForce RTX 3060 with 12GB RAM could malloc() less than 5GB.
 *  Program which runs fine on 1660 (CUDA 10.2, 1.0.0-beta7) with 6GB (2 GB free memory is present also), goes out of memory with 3060 (CUDA 11.2, 1.0.0-M1) with 12GB.
 *  Program crashes so often when applying arguments like `-Xms1G -Xmx2G -Dorg.bytedeco.javacpp.maxbytes=8G -Dorg.bytedeco.javacpp.maxphysicalbytes=10G`. Here might be no output in console, but rare JVM crash reports.

Ask if any additional info required. Up to dedicated desktop.

Check this program
```
package at.test;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang.NotImplementedException;
import org.bytedeco.javacpp.Pointer;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.nativeblas.NativeOps;
import org.nd4j.nativeblas.NativeOpsHolder;
import org.slf4j.LoggerFactory;

import ch.qos.logback.classic.Level;

public class CudaMallocTest
{
	public static void main(final String[ ] args)
	{
		((ch.qos.logback.classic.Logger) LoggerFactory.getLogger(ch.qos.logback.classic.Logger.ROOT_LOGGER_NAME))
				.setLevel(Level.ALL);
		Nd4j.zeros(1);
		test(true, 32);
		test(true, 16);
		test(true, 8);
		test(true, 4);
		test(true, 2);
		test(true, 1);
	}

	public static void test(final boolean device, final long sz)
	{
		final long mb = sz * 1024L * 1024L;

		if (!device)
		{
			throw new NotImplementedException();
		}

		int cnt = 0;
		System.out.println("Starting test " + sz + " mb");
		final NativeOps deviceNativeOps = NativeOpsHolder.getInstance().getDeviceNativeOps();
//		System.out.println(deviceNativeOps.getCachedMemory(0));
//		System.out.println(deviceNativeOps.getAvailableDevices());
		System.out.println("Free megabytes " + deviceNativeOps.getDeviceFreeMemory(0) / (1024L * 1024L));
//		System.out.println(deviceNativeOps.getDeviceFreeMemoryDefault());
//		System.out.println(deviceNativeOps.getDeviceTotalMemory(0));
		final List<Pointer> list = new ArrayList<>();
		try
		{
			while (true)
			{

				final Pointer mallocDevice = deviceNativeOps.mallocDevice(mb, 0, 0);
				list.add(mallocDevice);
				if (mallocDevice == null)
				{
					throw new RuntimeException("Megabytes " + cnt);
//					Thread.sleep(1000);
				}
				cnt += sz;
			}
		}
		catch (final Exception e)
		{
			System.out.println("Megabytes with size " + sz + " mb = " + cnt);
		}
		for (final Pointer p : list)
		{
			deviceNativeOps.freeDevice(p, 0);
		}
		System.out.println("Done test size " + sz + " mb");
	}

}
```

Should output something like
```
Starting test 32 mb
Free megabytes 10224
Megabytes with size 32 mb = 11465
Done test size 32 mb
Starting test 16 mb
Free megabytes 10224
Megabytes with size 16 mb = 11453
Done test size 16 mb
Starting test 8 mb
Free megabytes 10224
Megabytes with size 8 mb = 11430
Done test size 8 mb
Starting test 4 mb
Free megabytes 10224
Megabytes with size 4 mb = 11285
Done test size 4 mb
Starting test 2 mb
Free megabytes 10224
Megabytes with size 2 mb = 11242
Done test size 2 mb
Starting test 1 mb
Free megabytes 10224
Megabytes with size 1 mb = 11192
Done test size 1 mb
```

But outout is
```
<>
06:22:50.293 [main] INFO org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
06:22:50.300 [main] ERROR org.nd4j.common.config.ND4JClassLoading - Cannot find class [org.nd4j.linalg.jblas.JblasBackend] of provided class-loader.
06:22:50.301 [main] ERROR org.nd4j.common.config.ND4JClassLoading - Cannot find class [org.canova.api.io.data.DoubleWritable] of provided class-loader.
06:22:50.331 [main] ERROR org.nd4j.common.config.ND4JClassLoading - Cannot find class [org.nd4j.linalg.jblas.JblasBackend] of provided class-loader.
06:22:50.331 [main] ERROR org.nd4j.common.config.ND4JClassLoading - Cannot find class [org.canova.api.io.data.DoubleWritable] of provided class-loader.
06:22:52.325 [main] INFO org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for linear algebra: 32
06:22:52.357 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
06:22:52.357 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Cores: [8]; Memory: [8,0GB];
06:22:52.357 [main] INFO org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner - Blas vendor: [CUBLAS]
06:22:52.368 [main] INFO org.nd4j.linalg.jcublas.JCublasBackend - ND4J CUDA build version: 11.2.142
06:22:52.369 [main] INFO org.nd4j.linalg.jcublas.JCublasBackend - CUDA device 0: [NVIDIA GeForce RTX 3060]; cc: [8.6]; Total memory: [12884901888]
06:22:52.369 [main] INFO org.nd4j.linalg.jcublas.JCublasBackend - Backend build information:
 MSVC: 192829915
STD version: 201402L
CUDA: 11.2.142
DEFAULT_ENGINE: samediff::ENGINE_CUDA
HAVE_FLATBUFFERS
06:22:52.383 [main] TRACE org.nd4j.linalg.api.memory.deallocation.DeallocatorService - Starting deallocator thread 1
06:22:52.383 [main] TRACE org.nd4j.linalg.api.memory.deallocation.DeallocatorService - Starting deallocator thread 2
Starting test 32 mb
Free megabytes 10224
Megabytes with size 32 mb = 10432
Done test size 32 mb
Starting test 16 mb
Free megabytes 10224
Megabytes with size 16 mb = 10432
Done test size 16 mb
Starting test 8 mb
Free megabytes 10224
Megabytes with size 8 mb = 10392
Done test size 8 mb
Starting test 4 mb
Free megabytes 10224
Megabytes with size 4 mb = 10316
Done test size 4 mb
Starting test 2 mb
Free megabytes 10224
Megabytes with size 2 mb = 6102
Done test size 2 mb
Starting test 1 mb
Free megabytes 10224
Megabytes with size 1 mb = 5241
Done test size 1 mb

```

### PR DESCRIPTION
**Pull request by jljljl**
Changed overloaded methods. Commits require check.

### CODE REVIEW

**Comment by agibsonccc** [comment]
@jljljl could you update the associated HelperUtils method calls and tests as well to reflect the fix? Right now I have failing tests if we introduce this change.

**Comment by jljljl** [comment]
@agibsonccc I'll try

**Comment by agibsonccc** [comment]
@jljljl  happy to help if you get stuck. There's 2 batches of classes: the MKLDNN helpers in deeplearning4j-nn and the CUDNN helpers in deeplearning4j-cuda. There's tests in both modules that should pass.

**Comment by jljljl** [comment]
@agibsonccc try now. If you have any troubles with it, you can change code. It also requires manual check.

**Comment by agibsonccc** [comment]
@jljljl I'm not really sure what changed...could you just run this test and make sure it passes? That's really all that needs to be done. There's no manual work here and you can verify it on your own. I keep getting this:
```
C:\Users\agibs\Documents\GitHub\dl4j-PR-split\deeplearning4j\deeplearning4j\deeplearning4j-nn\src\main\java\org\deeplearning4j\nn\layers\HelperUtils.java:57:46
java: no suitable method found for createNewInstance(java.lang.String,java.lang.Class<capture#1 of ? extends org.deeplearning4j.nn.layers.LayerHelper>,java.lang.Object[])
    method org.deeplearning4j.common.config.DL4JClassLoading.<T>createNewInstance(java.lang.String) is not applicable
      (cannot infer type-variable(s) T
        (actual and formal argument lists differ in length))
    method org.deeplearning4j.common.config.DL4JClassLoading.<T>createNewInstance(java.lang.String,java.lang.Object[]) is not applicable
      (cannot infer type-variable(s) T
        (actual and formal argument lists differ in length))
    method org.deeplearning4j.common.config.DL4JClassLoading.<T>createNewInstance(java.lang.String,java.lang.Class<? super T>) is not applicable
      (cannot infer type-variable(s) T
        (actual and formal argument lists differ in length))
    method org.deeplearning4j.common.config.DL4JClassLoading.<T>createNewInstance(java.lang.String,java.lang.Class<? super T>,java.lang.Object...) is not applicable
      (cannot infer type-variable(s) T
        (argument mismatch; java.lang.Class<capture#1 of ? extends org.deeplearning4j.nn.layers.LayerHelper> cannot be converted to java.lang.Class<? super T>))
    method org.deeplearning4j.common.config.DL4JClassLoading.<T>createNewInstance(java.lang.String,java.lang.Class<? super T>,java.lang.Class<?>[],java.lang.Object[]) is not applicable
      (cannot infer type-variable(s) T
        (actual and formal argument lists differ in length))
```

when running this test. https://github.com/eclipse/deeplearning4j/blob/203c5434b30905dc8b5b4dacf254d5f35bb4487d/deeplearning4j/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/layers/HelperUtilsTest.java#L34

**Comment by jljljl** [comment]
@agibsonccc here is no method createNewInstance(java.lang.String,java.lang.Class<capture#1 of ? extends org.deeplearning4j.nn.layers.LayerHelper>,java.lang.Object[]). Tell me what method. What method is correct for it?

**Review by agibsonccc — APPROVED** [review]

**Comment by agibsonccc** [comment]
@jljljl  with a bit of running the tests, I found out that this actually works fine. I jus thad 1 minor correction in one o fthe tests that was on me to fix anyways. Merging this.

**Pull request merged**
