### PR TITLE
Update docs for keras model import

### PR DESCRIPTION
**Pull request by maxpumperla**
- Updated original doc
- Added feature support page

### CODE REVIEW

**Comment by tomthetrainer** [comment]
I would suggest that we begin to use a template for all documentation. 

Could these pages fit into the template linked below?

Basically the template enforces a structure of: 

Table of contents
Description
Details

If the Doc does not fit into the template structure for some reason, then propose another template for that style of doc. 

https://deeplearning4j.org/doc_templates/template_basic

**Comment by tomthetrainer** [comment]
Besides the Template comment, everything looks good.

**Comment by maxpumperla** [comment]
@tomthetrainer thanks, wasn't aware we already had these templates.

**Comment by tomthetrainer** [comment]
Great work, thanks.

**Pull request merged**
