### PR TITLE
Add an option to deploy from the build-dl4j-script

### PR DESCRIPTION
**Pull request by huitseeker**
With this option alone I've been able to push a build repo to completion. This PR helps with the last step. 

1. set up a maven repo in your favorite nexus server
https://books.sonatype.com/nexus-book/2.11/reference/config-sect-new-repo.html

2. Configure it to allow re-uploads (a.k.a overwriting assets or multiple versions of the same asset)
Configure it to allow snapshots & releases.
In Nexus 3, this is the setup you want :
https://i.imgur.com/9urlzFl.png

3. set a server section in your ~/.m2/settings.xml:

```
   <servers>
    <server>
      <id>mynexus.repo</id>
      <username>my.password</username>
      <password>my.password</password>
    </server>
    </servers>
```

4. 
run 
```
./build-dl4j-stack.sh -r update --deploy --mvnopts "-DaltDeploymentRepository=mynexus.repo::default::http://url.to.my.nexus.repo"
```

/cc @emsixteeen

### CODE REVIEW

**Comment by huitseeker** [comment]
Adding @turambar because we're talking about this

**Comment by saudet** [comment]
The issue with this though is that the binaries that get created have a chance of not working anywhere else than on the machine they were built on, so I don't really see the point of the script, unless it's meant to be used on customer's machines or something along those lines?

**Comment by turambar** [comment]
This looks good to me!

@saudet this is in reference to a very specific, one-off need.

**Comment by saudet** [comment]
@turambar I don't see any harm in merging this though, sure :) Press the little "approve" button so this can get merged!

**Pull request merged**
