### PR TITLE
configuration serialization - layer factory

### PR DESCRIPTION
**Pull request by EronWright**
Here is the next step in a series of improvements for high-fidelity serialization of `MultiLayerConfiguration`.    The `NeuralNetConfiguration` no longer takes `LayerFactory` directly, instead it takes a set of layer configuration types (`RBM`, `AutoEncoder`, etc).   `LayerFactory` continues to be used as before, but later when a network is actually constructed.   `LayerFactories` and `DefaultLayerFactory` contain logic to translate the configuration objects.

A nice aspect of this change is that layer-specific configuration properties (such as `ConvolutionType`) could be moved to layer-specific configuration classes.   This may help with the goal of improving the stability of the API.

I suggest we move `LayerFactory` out of the API package, since it is now an implementation detail.

Note that some layer types aren't supported (`ConvolutionLayer`/`RNTN`/`SubsamplingLayer`).   I will update the PR once Adam's changes related to those layers come in.

### CODE REVIEW

**Comment by agibsonccc** [comment]
Get this passing and I'll merge it: https://github.com/deeplearning4j/deeplearning4j/blob/f4a8c00bb95bbaf8d9565290e58dee7a2899ef4f/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/conf/NeuralNetConfigurationTest.java#L37-37

**Comment by agibsonccc** [comment]
Everywhere you put Random is also wrong. If you use Random instead of the explicit nd4j random the definitions clash.

**Comment by EronWright** [comment]
I too am anxious for NeuralNetConfigurationTest to pass.   The equality check is failing at the stepfunction test ([#L594](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/conf/NeuralNetConfiguration.java#L594).   It probably hasn't passed since Dec/14.   I'll update the PR with a fix for stepfunction (similar to these other fixes).

**Comment by EronWright** [comment]
With the stepfunction fixed, `NeuralNetConfigurationTest` passes:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.deeplearning4j.nn.conf.NeuralNetConfigurationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.501 sec - in org.deeplearning4j.nn.conf.NeuralNetConfigurationTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

JSON output:
```
{
  "sparsity" : 0.0,
  "useAdaGrad" : true,
  "lr" : 0.10000000149011612,
  "corruptionLevel" : 0.30000001192092896,
  "numIterations" : 1000,
  "momentum" : 0.5,
  "l2" : 0.0,
  "useRegularization" : false,
  "momentumAfter" : null,
  "resetAdaGradIterations" : -1,
  "numLineSearchIterations" : 100,
  "dropOut" : 0.0,
  "applySparsity" : false,
  "weightInit" : "VI",
  "optimizationAlgo" : "CONJUGATE_GRADIENT",
  "lossFunction" : "RECONSTRUCTION_CROSSENTROPY",
  "constrainGradientToUnitNorm" : false,
  "rng" : {
    "default" : {
      "seed" : 1430711862910
    }
  },
  "dist" : {
    "normal" : {
      "mean" : 1.0,
      "std" : 1.0
    }
  },
  "stepFunction" : {
    "default" : { }
  },
  "layer" : {
    "RBM" : { }
  },
  "nIn" : 0,
  "nOut" : 0,
  "activationFunction" : "sigmoid",
  "visibleUnit" : "BINARY",
  "hiddenUnit" : "BINARY",
  "k" : 1,
  "weightShape" : [ 0, 0 ],
  "filterSize" : [ 2, 2, 2, 2 ],
  "stride" : [ 2, 2 ],
  "kernel" : 5,
  "batchSize" : 0,
  "minimize" : false,
  "convolutionType" : "MAX"
}
```

**Pull request merged**
