### PR TITLE
Please upload the translation of https://deeplearning4j.org/ja/ai-machinelearning-deeplearning.

### PR DESCRIPTION
**Pull request by eiida**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Reviewed the [Contributing Guidelines](https://github.com/deeplearning4j/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.
- [ ] Ran mvn formatter:format (see [formatter instructions](http://code.revelc.net/formatter-maven-plugin/examples.html#Setting_Source_Files) for targeting your specific files).

### CODE REVIEW

**Comment by eiida** [comment]
Please upload the translation of https://deeplearning4j.org/ja/ai-machinelearning-deeplearning.

**Comment by agibsonccc** [comment]
@saudet any updates here?

**Comment by saudet** [comment]
@eiida about.md and word2vec.md have also been updated, should we merge those as well?

**Comment by eiida** [comment]
@saudet  Yes please do so.

**Comment by eiida** [comment]
Please upload the Japanese translation of https://github.com/deeplearning4j/deeplearning4j/blob/gh-pages/bagofwords-tf-idf.md:

https://github.com/eiida/deeplearning4j/blob/gh-pages/ja/bagofwords-tf-idf.md

**Comment by saudet** [comment]
@eiida You'll need to create a new pull request for that.

**Comment by eiida** [comment]
@saudet I created as follows. Please let me know how if this is wrong.
https://github.com/deeplearning4j/deeplearning4j/pull/4034

**Pull request merged**
