### PR TITLE
new branch for bleeding spark

### PR DESCRIPTION
**Pull request by tripiana**
As requested by @agibsonccc bleeding spark version

### CODE REVIEW

**Comment by tripiana** [comment]
checks have failed because it cannot download bleeding versions of nd4j and Canova

**Comment by tripiana** [comment]
I recommend checking the diff between dl4j-spark/dl4j-spark-bleeding and the diff between dl4j-spark-ml/dl4j-spark-ml-bleeding before accepting the commit. Just to see some code modifications I've done so as to be able to compile.

**Comment by tripiana** [comment]
Compiled with java 1.8, Spark 1.5.1, Hadoop 2.7.1

**Comment by agibsonccc** [comment]
Have you tested this against your cluster yet to see if it runs the jobs you were expecting?

**Comment by tripiana** [comment]
Not yet. End of the day at work. On Monday I'll try to deploy it. I'm
sysadmin, so I need a good and easy test to run. Do you have any? Thanks!!

**Comment by agibsonccc** [comment]
I would recco just trying to run spark-submit against a local newer version of spark. That's something you should be able to setup you r laptop. Let's coordinate this on gitter. I'll keep an eye out.

**Comment by tripiana** [comment]
Ok. I'll do it on Monday morning. Pole position in my todo list, I promise.

**Pull request closed without merging**
