### PR TITLE
adding S3 repo abilities

### PR DESCRIPTION
**Pull request by emsixteeen**
## What changes were proposed in this pull request?

Adding ability to push to S3

### CODE REVIEW

**Comment by huitseeker** [comment]
@agibsonccc @emsixteeen An S3 repo is a polysemic appellation. What does it mean?
Using S3 as a git repository ? RPM repository ? deb / APT repository ? maven repository ?

**Comment by emsixteeen** [comment]
The change/s is/are in a POM file under Profiles -> DistributionManagement
-> SnapshotRepository ... it's to support S3 as a destination for a Maven
repository [for snapshots].

Best,
-Michael

On Mon, Nov 20, 2017 at 2:25 PM, François Garillot <notifications@github.com

**Comment by emsixteeen** [comment]
dunno -- i'll check if it can be done via settings.xml (when I tried a while back I was getting XML validation issues about the <build/> tag(s) within settings.xml, and just switched it to the POM).

**Pull request merged**
