### PR TITLE
Update docs for parallel early stopping

### PR DESCRIPTION
**Pull request by crockpotveggies**
Addresses https://github.com/deeplearning4j/deeplearning4j/issues/3029.

For some reason Github doesn't recognized previously merged commits. Only the most recent 3 apply.

### CODE REVIEW

**Comment by agibsonccc** [comment]
Might be easier to link to an example here?

**Comment by crockpotveggies** [comment]
Updated.

**Comment by crockpotveggies** [comment]
@huitseeker does that meet your needs?

**Comment by huitseeker** [comment]
No, you should have exactly four commits in here, not 47, irrespective of your merge. I've prepared a branch in my fork with how that should look like. Please `git remote add huitseeeker git://github.com/huitseeker/deeplearning4j.git`, then `git remote update`, and finally `git reset --hard huitseeker/pr/3034`.

If you want to backup your original branch, do some git checkout -b in between.

**Comment by huitseeker** [comment]
Closing since this is merged https://github.com/deeplearning4j/deeplearning4j/pull/3045

**Pull request closed without merging**
