### PR TITLE
Fix dependency versions for datavec-uberjar

### PR DESCRIPTION
**Pull request by sshepel**

### CODE REVIEW

**Comment by saudet** [comment]
That's only going to work with a single version of Scala and Spark, so if that's alright, ok, but what is the goal of this?

**Comment by sshepel** [comment]
@saudet you mean `datavec-spark`? The goal of this PR fix broken master...

**Comment by saudet** [comment]
Right, but whomever created datavec-uberjar should fix it. If nobody cares, just disable it from the CI.

**Comment by sshepel** [comment]
Fixed in #6360 and #6204

**Pull request closed without merging**
