### PR TITLE
fix concurrency issue in ticketing framework

### PR DESCRIPTION
**Pull request by pza94**
## What changes were proposed in this pull request?

https://github.com/eclipse/deeplearning4j/issues/9534
fix addressing concurrency problems in ticketing framework

## How was this patch tested?

Was not.

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ X] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

### CODE REVIEW

**Comment by pza94** [comment]
this might be sub-optimal, since it doesn't increase the available thread count right away when a thread finishes its task, but at least takes care of the concurrency issues.

Possibly bit more efficient would be, to increment the _available (thread count) variable for all but the last task in the for-loop, and then increment it once more after the ticket is put back on the queue. ?

**Comment by quickwritereader** [comment]
thanks @pza94 
I will recheck that ticket threading logics and also your potential fix

**Comment by quickwritereader** [comment]
alright, I think this fix is feasible.  I checked the source. It seems this thread pool was implemented to achieve   a  **restricted** fork-join model unlike standard OMP

**Review by quickwritereader — DISMISSED** [review]

**Comment by pza94** [comment]
We started using the changes I proposed in production, because the segfaults we were getting, were critical. However, I would like to point out that this really is not a very efficient solution:

Let's say if a ticket acquired 2 threads, and one of them runs for 1 second and the other runs for an hour then both of those threads will be locked down for an hour. In our specific prod use cases this wouldn't happen, so we didn't put much effort into making this efficient, but this definitely could be improved by refactoring the `tryAcquire` method and maybe the `_tickets` queue in the `ThreadPool` class. We didn't want to commit to those changes ourselves.

**Comment by quickwritereader** [comment]
I see. Mostly its used for splitting into equal parts 
.
Also could you specify the device and os in which you were getting segs 
I think maybe somehow its related with atomic variable.
assembly should be checked for atomic variable operations :

--var
++var
var+=n

**Comment by pza94** [comment]
os is ubuntu16
device is x86-64 cpus (various amd and  intel CPUs).

`I think maybe somehow its related with atomic variable.`
I wouldn't think so. In my view the issue is that the 2 operations: incrementing `_available` and putting back the ticket in the queue does not happen atomically. Or in fact just putting back the ticket first and then incrementing should suffice as well, given how the `tryAcquire` method checks for thread-availability.

**Comment by quickwritereader** [comment]
I see. and you mentioned that somehow the tickets are exhausted.

**Comment by pza94** [comment]
That is our theory at least, based on the segfault dump and our notes in the related issue. Couldn't verify it though, feels like a nasty race condition that is not easy to reproduce.

**Comment by quickwritereader** [comment]
yes let assume
we have 2 threads
2 parallel executions.
in that case
there is possibility that the current order might affect null ticket

**Comment by quickwritereader** [comment]
so doubling ticket size can be pretty good solution for such cases.
otherwise there should be condition for checking the ticket queue size and return as nonavailable in the case its exhausted

**Comment by quickwritereader** [comment]
Could you verify those possible fix above 
theoritically ticket being none is possible due to releasing threads before the ticket

**Comment by quickwritereader** [comment]
https://github.com/eclipse/deeplearning4j/blob/573cdfc71684ffd88f1d20c278d181dac1e4f8dd/libnd4j/include/execution/impl/ThreadPool.cpp#L157

`    if (_available >= numThreads) {` 
coudl be replcaed by
`if (_available >= numThreads && _tickets.size()>0) {`

Furthermore, to make such cases happen rarely, an additional ticket could be pushed in the constructor as well. 

. the other solution could be to push twice more ticket

**Comment by pza94** [comment]
We considered doubling the initial ticket count. In theory (in some crazy scenario) I think it's possible that you'll end up running into the same issue, but in practice it would never really happen.

fx. say max_thread_count=1, then you have 2 tickets initially:

* (Java thread1) acquire 1 ticket, that uses 1 thread. when that task is finished it increments `_available` and the OS unschedules the thread before giving back the queue. 
* at this point `_available==1` and ticket count is also 1
* (Java thread2) same as in first point but in a different (Java) thread AND OS hadn't rescheduled `Java thread1`.
* (Java thread3) does will segfault
You gotta be real unlucky for this to happen though.

`checking the ticket queue size and return as nonavailable` seems fair to me

**Comment by quickwritereader** [comment]
@pza94 if possible could you check the above fix.

as I confirm that there can be potential ticket exhaustion.
the current fix is pretty well. that's why I accepted, as this thread pool is acting like fork-join style.
but if the above fix can work it can help with the potential sub-optimal case you mentioned

**Comment by pza94** [comment]
> 

this is the best probably

**Comment by pza94** [comment]
> https://github.com/eclipse/deeplearning4j/blob/573cdfc71684ffd88f1d20c278d181dac1e4f8dd/libnd4j/include/execution/impl/ThreadPool.cpp#L157
> 
> ` if (_available >= numThreads) {` coudl be replcaed by `if (_available >= numThreads && _tickets.size()>0) {`
> 
> Furthermore, to make such cases happen rarely, an additional ticket could be pushed in the constructor as well.
> 
> . the other solution could be to push twice more ticket

this is the best probably

**Comment by quickwritereader** [comment]
yes, let's see if it helps.

**Comment by quickwritereader** [comment]
@pza94 could you apply the discussed fix in the current Pr , if it works
otherwise just inform us. we will merge this as a fix.
thanks. well done

**Comment by pza94** [comment]
sure, I'll submit it later today

**Comment by pza94** [comment]
are the comments sufficient/too much/explain well enough the concurrency issues?

**Review by quickwritereader — APPROVED** [review]

**Comment by quickwritereader** [comment]
yes, they are.
thanks. well done

**Review by quickwritereader — APPROVED** [review]

**Comment by pza94** [comment]
note: if you want to run an extra mile with testing this you can try (on linux) forcing a context switch before releasing the ticket and have many java threads request operations that use only a few (or preferably just one) thread, like so:
```
void Ticket::waitAndRelease() {
  for (uint32_t e = 0; e < this->_acquiredThreads; e++) {
    // block until finished
    _interfaces[e]->waitForCompletion();

    // mark available
    _interfaces[e]->markAvailable();

    // increment availability counter
    ThreadPool::getInstance().release();
  }
  sched_yield();
  // return this ticket back to the pool
  ThreadPool::getInstance().release(this);
}
```
I can't really afford to play with this myself, but I think this should trigger the behavior I described. And then test that it doesn't happen with the changes proposed here. Up to you

**Review by agibsonccc — APPROVED** [review]

**Pull request merged**
