### PR TITLE
Reshape : Use negative ints for order

### PR DESCRIPTION
**Pull request by farizrahman4u**
Use `-99`, `-102` instead of `99`, `102` to represent `'c'` and `'f'` respectively.

### CODE REVIEW

**Comment by AlexDBlack** [comment]
What's the idea here?
Looks like order arg is required (line 21) - so is there a benefit to making it negative?
I'm just hestiant to introduce op-specific special cases like this unless they are really required.

**Comment by AlexDBlack** [comment]
> we've discussed this with fariz earlier: idea is to avoid misinterpretation of order and actual reshape dimension value.

If order is a required arg (as it seems to be, by my reading of the code), then I don't think it's needed.

Maybe it doesn't matter in practice as users won't need to use dynamiccustomop (instead will use the java class to call it), but it seems like one of those special cases that could waste dev time, by not following existing conventions.
Anyway, I won't push the issue further. Just my thoughts.

**Comment by farizrahman4u** [comment]
@AlexDBlack  It is not required but optional.. which means an actual dimension of 99 can be misinterpreted as ordering. (Right now we cant reshape an array to shape (99, 10) on both ends - java and cpp)

**Comment by AlexDBlack** [comment]
> It is not required but optional

Ok, so looking at the code again: it *is* required for 1 input array arg, but not 2.
Negatives don't help with the second case.

If it should be optional for both, then we also need to fix this check, as we won't be able to reshape to rank 1 matrix without always specifying an order arg otherwise:
https://github.com/deeplearning4j/deeplearning4j/blob/f1d57a86885aedc50717a4b071e9f5d43227d47c/libnd4j/include/ops/declarable/generic/shape/reshape.cpp#L21

**Pull request merged**
