### PR TITLE
Bugfix 9727

### PR DESCRIPTION
**Pull request by j-d-o**
## What changes were proposed in this pull request?

A bugfix to https://github.com/eclipse/deeplearning4j/issues/9727 in form of a pull request as suggested by https://github.com/agibsonccc

## How was this patch tested?

no tests touched or run - just the obvious wrong variable name corrected

### CODE REVIEW

**Comment by agibsonccc** [comment]
@j-d-o this looks good. Mind signing the ECA? (Sorry eclipse foundation :) see: https://deeplearning4j.konduit.ai/multi-project/how-to-guides/contribute/eclipse-contributors

**Comment by j-d-o** [comment]
I did, anything else ?

**Review by agibsonccc — APPROVED** [review]

**Comment by agibsonccc** [comment]
Great job! Thanks merged!

**Comment by j-d-o** [comment]
Thank you ... Im hoping for a next release soon. Thank you all for doing open source in the first place!

**Pull request merged**
