### PR TITLE
#9050 fixes

### PR DESCRIPTION
**Pull request by jljljl**
Fixed hashCode() NullPointerException, bug with missed vertical and horizontal iteration, regularization bug. Consider applying own changes to code instead of merging it. Ignore "final" modifier replacements when realizing changes.

### CODE REVIEW

**Comment by jljljl** [comment]
Fix #9050

**Comment by agibsonccc** [comment]
@jljljl thanks for the pull request! Do you mind signing the eclipse ECA? https://www.eclipse.org/legal/ECA.php

**Comment by jljljl** [comment]
@agibsonccc Busy a bit. It may take few days for me to manage eclipse stuff. I suggest you to check changes and make one commit instead of multiple.

**Comment by agibsonccc** [comment]
@jljljl  it takes just a few seconds to sign the ECA. Sorry you don't have time to do so. I appreciate the contribution and would like you to get credit for it if possible.

**Comment by jljljl** [comment]
@agibsonccc It requires some manual check. #feea1f9 commit contains changes for ComputationGraph regularization generation. By default, method configureBaseLayer() may replace custom regularizations by parameter list. Please check #feea1f9 commit. Commit fixes it but may miss concept of that method. This is only changes i made to that file, but here is much more lines marked as changed by git.
Due to a reasons like that and messed commits like "Others", "Reversed "others" commit" which i did with a missclick i would like to undo that commits and make one or few compact commits contains all that changes. Auto save actions and such features sometimes may mess things.
Also #06a80a1 commit requires check cause it may contain bug. Please notice me after you approve those commits. Also i am not sure i got you. I would prepare valid changes while waiting for answer.

**Comment by jljljl** [comment]
Fixing commits, closing request

**Pull request closed without merging**
