### PR TITLE
Merge master to upstream

### PR DESCRIPTION
**Pull request by AlexDBlack**

### CODE REVIEW

**Comment by aeiplatform** [comment]
Why did you make methods getTrainIterator() and getTestIterator() in class DataSetIteratorSplitter deprecated?
Is there any equivalent substitution to have same behavior of pseudo example:

`graph.fit(data.getTrainIterator(), EPOCH);`
`graph.evaluate(data.getTestIterator());`

**Comment by raver119** [comment]
Because now you can have any number of iterators, not only 2.

**Comment by aeiplatform** [comment]
If anybody uses non deprecated constructor DataSetIteratorSplitter(@NonNull DataSetIterator baseIterator, long totalBatches, double ratio) then that method will cause NPE.

**Comment by aeiplatform** [comment]
Same defect in MultiDataSetIteratorSplitter.

**Pull request merged**
