### PR TITLE
Fix Nullpointer Exception

### PR DESCRIPTION
**Pull request by cyberbeat**
For me, this fixes
https://github.com/eclipse/deeplearning4j/issues/9148

## What changes were proposed in this pull request?

A test on null was missing

## How was this patch tested?

I tested my change, and now my code works fine, and gives good learning results.

### CODE REVIEW

**Comment by agibsonccc** [comment]
@cyberbeat could you please sign the eclipse CLA? Thanks!

**Comment by cyberbeat** [comment]
Signed now

**Comment by agibsonccc** [comment]
@cyberbeat  apologies but this isn't complete yet. See the tip:

Please check that each commit has the 'Signed-off-by' footer as part of the commit message. This can be added by checking out the offending commit and using git commit -a -s.
Additional information on contributing to Eclipse projects can be found on the Eclipse wiki under Development Resources/Handling Git Contributions, or under Development Resources/Contributing via Git for new committers.

**Comment by cyberbeat** [comment]
I would be glad, if someone else could apply this simple change, there is nothing to worry about intellectual properties for such a patch.

**Comment by agibsonccc** [comment]
@cyberbeat sorry it's just standard eclipse foundation policy. I know it's a bit annoying, but it doesn't take that long and I'd like you to get credit for what you did.

**Comment by agibsonccc** [comment]
Shame I have to close this. I'll work on merging this fix later.

**Review by agibsonccc — APPROVED** [review]

**Comment by agibsonccc** [comment]
Eclipse has gotten rid of this requirement so I have merged this PR.

**Pull request merged**
