### PR TITLE
Upgrades solr, fixes https://github.com/eclipse/deeplearning4j/issues…

### LINKED ISSUE #9297: Restore solrj-tests later
#### Issue Description
Right now, the test in the solrj module is preventing a successful build (could be due to a temp outage?), due to this error:
```
R] Failed to execute goal on project deeplearning4j-dataimport-solrj: Could not resolve dependencies for project org.deeplearning4j:deeplearning4j-dataimport-solrj:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.apache.solr:solr-test-framework:jar:7.7.1 -> org.restlet.jee:org.restlet:jar:2.3.0: Failed to read artifact descriptor for org.restlet.jee:org.restlet:jar:2.3.0: Could not transfer artifact org.restlet.jee:org.restlet:pom:2.3.0 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [maven-restlet (http://maven.restlet.org, default, releases+snapshots), apache.snapshots (http://repository.apache.org/snapshots, default, disabled)] -> [Help 1]
2021-05-08T00:02:42.7430866Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project deeplearning4j-dataimport-solrj: Could not resolve dependencies for project org.deeplearning4j:deeplearning4j-dataimport-solrj:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at or
```
We can restore the test at a later date, but for now it's been deleted.

Please describe our issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* Platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Additional Information

Where applicable, please also provide:

* Full log or exception stack trace (ideally in a Gist: gist.github.com)
* pom.xml file or similar (also in a Gist)

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

### PR DESCRIPTION
**Pull request by agibsonccc**
Fixes https://github.com/eclipse/deeplearning4j/issues/9297

Upgrades the solr version

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ ] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [ ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ ] Created tests for any significant new code additions.
- [ ] Relevant tests for your changes are passing.

### CODE REVIEW

**Review by treo — APPROVED** [review]

**Review by treo — CHANGES_REQUESTED** [review]
You should actually re-enable the test you've deleted because of the problem.

**Comment by agibsonccc** [comment]
@treo it's still disabled due to an unrelated problem with junit 4/5. I plan on enabling it later. Before I actually had deleted the tests as a whole and removed the dependencies.

**Comment by treo** [comment]
@agibsonccc If you've deleted it before, and this only changes a version, I where is the disabled test then?

**Comment by agibsonccc** [comment]
@treo that was in my closed PR. Since that change wasn't actually needed (just updating the version was needed since it was purely a version dependent problem) I just kept it in its previous state to be updated for junit 4 to 5.

**Review by treo — APPROVED** [review]
Ah, if that wasn't merged, that makes sense.

**Pull request merged**
