### PR TITLE
FEATURE: change API of WordVectorSerializer. Add posibility to read m…

### PR DESCRIPTION
**Pull request by hosuaby**
Allow to read model from Stream by WordVectorSerializer.

### CODE REVIEW

**Comment by AlexDBlack** [comment]
Thanks for the fixes. Looks like there's still a test failure in deeplearning4j-nlp:

CPU:
```
[2020-05-02T18:02:25.579Z] Failed tests: 
[2020-05-02T18:02:25.579Z]   FastTextTest.testWordsStatistics:224 expected:<0.1667751520872116> but was:<0.16687846183776855>
```

CUDA:
```
[2020-05-02T18:31:04.319Z] Failed tests: 
[2020-05-02T18:31:04.319Z]   FastTextTest.testWordsStatistics:224 expected:<0.1667751520872116> but was:<0.16691969335079193>
```

I have downloaded and attached the full build log, if you need more info:
[Uploading PR8908_CI_build_log_linux_x86-64.txt…]()

I'd say it's probably just the compounded effect of minor differences due to parallelization - i.e., different number of threads on your machine vs. CI machines. Tiny numerical differences can add up over thousands of sequential operations like we probably have here.

Actual values look close enough to me to be correct, so I say we lower the threshold to say 2e-3 and run tests again.

**Comment by hosuaby** [comment]
@AlexDBlack Oki. I check those tests both with CPU and CUDA and look to lower threshold

**Comment by hosuaby** [comment]
@AlexDBlack  I have this kind of exception during build:
```
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://dl4jtestresources.blob.core.windows.net/resources/big/raw_sentences.txt.gzx.v1
```
Do you have idea how to solve it? On my laptop there is no that exception, but on my desctop I can build project.

**Comment by hosuaby** [comment]
Hello @AlexDBlack. Sorry for trouble. I systematically get
Server returned HTTP response code: 403 for URL: https://dl4jtestresources.blob.core.windows.net/resources/big/raw_sentences.txt.gzx.v1 while try to build project on my desctop. Surprisingly, that same build works on my laptop. Do you have idea how to solve this problem ?

**Comment by hosuaby** [comment]
P.S. Looks like there is a cache for resources in folder ~/.cache/nd4j/test_resources that was somehow filled on my laptop, but can't on desktop.

**Comment by hosuaby** [comment]
I lowered threshold to requested 2e-3. Looks like tests in `deeplearning4j-nlp-parent` are very unreliable. I experienced regular failures in test `Word2VecTestsSmall#testW2VEmbeddingLayerInit` while testing on CUDA. It appeares need to wait a little before condition `assertEquals(net.params(), restored.params());` becomes true.

Anyway, looks like, tests passing more often now, at least on my machines. So I updated PR.

P.S. please, check your Azure. I had problems while downloading test resources. I copied cached resources from my laptop (they was downloaded before) to my desktop to make tests with CUDA?

**Comment by treo** [comment]
> P.S. please, check your Azure. I had problems while downloading test resources. I copied cached resources from my laptop (they was downloaded before) to my desktop to make tests with CUDA?

I think you might be using an outdated dl4j-test-resources repository. You should be using https://github.com/KonduitAI/dl4j-test-resources

**Comment by hosuaby** [comment]
Thanks @treo. It was really the case.

**Review by AlexDBlack — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
