### PR TITLE
add-tests Added new Unit Tests.

### PR DESCRIPTION
**Pull request by TheRealHaui**
## What changes were proposed in this pull request?

None, just added Unit Tests to cover previously uncovered logic.

## How was this patch tested?

Tests were executed.

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ x] Reviewed the [Contributing Guidelines](https://github.com/deeplearning4j/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [ x] Created tests for any significant new code additions.
- [ x] Relevant tests for your changes are passing.
- [x ] Ran mvn formatter:format (see [formatter instructions](http://code.revelc.net/formatter-maven-plugin/examples.html#Setting_Source_Files) for targeting your specific files).

### CODE REVIEW

**Comment by TheRealHaui** [comment]
No problem!
However, I am encountering heavy problems installing openBLAS currently.
So it may take a while.
...

**Comment by saudet** [comment]
@TheRealHaui You shouldn't need to install OpenBLAS. What problems are you encountering exactly?

**Comment by TheRealHaui** [comment]
@saudet 
Thank your for your kind response and your offered help!

I cannot "mvn install -DskipTests" the nd4j project on the command line because the nd4j-native module fails: "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (libnd4j-checks) on project nd4j-native: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]"

Looking above tells me:
selection_002

I am using Linux Mint 18 and Maven 3.3.9.
Furthermore I installed the appropriate Linux headers and the build essentials.

Your help is very appreciated!

**Comment by AlexDBlack** [comment]
I didn't realize we had duplicate MathUtils... agree that we should remove the DL4J one in favour of the ND4J one.

@TheRealHaui you'll need to build libnd4j from source first: https://github.com/deeplearning4j/libnd4j
and don't forget the ```export LIBND4J_HOME=/path/to/libnd4j/``` before building nd4j.
Go here if you run into issues: https://gitter.im/deeplearning4j/deeplearning4j/earlyadopters

**Comment by agibsonccc** [comment]
@TheRealHaui beyond alex's suggesitons I'll approve the clustering related changes. Thanks for the PR!

**Comment by huitseeker** [comment]
@TheRealHaui you need to download and compile libnd4j aside nd4j (i.e. libnd4j, nd4j are in the same directory), and build it by running the `./buildnativeoperations.sh` script at the root of the libnd4j repo. 

For more details, the doc is http://nd4j.org/source

**Comment by huitseeker** [comment]
Hi @TheRealHaui any news on this one?

**Comment by TheRealHaui** [comment]
Sorry, haven't had time on this.
I am planning to solve it during the next week.

**Pull request closed without merging**
