### PR TITLE
[WIP] Invert stride in IntervalIndex.reverse(), v2

### LINKED ISSUE #7276: IntervalIndex.reverse() does not work
#### Issue Description
This test:

    @Test
    public void testReverseIntervalIndex() {

        INDArray array = Nd4j.create(new double[] { 0, 1, 2, 3, 4, 5 });

        INDArrayIndex interval = NDArrayIndex.interval(1, 4);
        interval.reverse();

        array.get(interval).toString();
    }

throws:
```
java.lang.IndexOutOfBoundsException: 6
	at org.bytedeco.javacpp.indexer.Indexer.checkIndex(Indexer.java:94)
	at org.bytedeco.javacpp.indexer.DoubleRawIndexer.get(DoubleRawIndexer.java:59)
	at org.nd4j.linalg.api.buffer.BaseDataBuffer.getDouble(BaseDataBuffer.java:1239)
	at org.nd4j.linalg.api.shape.Shape.getDouble(Shape.java:682)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:1917)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:4435)
	at org.nd4j.linalg.string.NDArrayStrings.vectorToString(NDArrayStrings.java:243)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:182)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:150)
	at org.nd4j.linalg.string.NDArrayStrings.format(NDArrayStrings.java:127)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:5774)
```

From reading `IntervalIndex`, it seems `next()` does not invert `stride`, not sure how this is supposed to work.

#### Version Information

* Deeplearning4j version: sonatype repo 1.0.0 snapshot: 1.0.0-20190308.084722-15882
* platform information (OS, etc): linux x86_64
* CUDA version, if used: N/A
* NVIDIA driver version, if in use: N/A

Aha! Link: https://skymindai.aha.io/features/ND4J-89

### PR DESCRIPTION
**Pull request by rnett**
## What changes were proposed in this pull request?

Invert stride in IntervalIndex.reverse()

Fixes #7276

## How was this patch tested?

Unit tests

### CODE REVIEW

**Comment by rnett** [comment]
Tests are not passing, don't merge.

**Comment by rnett** [comment]
Looking into things, it looks like reverse needs some significant work.
* `hasNext()` needs to be updated to work with backwards iterators
* `next()`/`index` needs to be updated

**Comment by rnett** [comment]
Going to have to re-create again to fix build issues.

**Comment by AlexDBlack** [comment]
Commented here so comment doesn't get lost: https://github.com/deeplearning4j/deeplearning4j/issues/7276#issuecomment-477106460

**Pull request closed without merging**
