### PR TITLE
Parallelize RecordReaderDataSetIterator

### PR DESCRIPTION
**Pull request by crockpotveggies**
## What changes were proposed in this pull request?

This PR parallelizes the RRDSI next(num) operation. DataSets returned are guaranteed fair order.

## How was this patch tested?

*In progress*. Record readers will need to be thread-safe.

### CODE REVIEW

**Comment by crockpotveggies** [comment]
Hmm, I guess I could use `Thread.currentThread()` to determine which thread in the thread pool is being used. And then I can assign a pipeline to that specific thread if it hasn't been seen before.

**Comment by crockpotveggies** [comment]
@AlexDBlack hopped on the phone with raver and he walked me through a solution that solves your concern. Basically, we can parallelize RRDSI w/ fair order *after* calling RR.next(). Internally on IRR, we can modify it so it works like AsyncInterator and performs prefetch. Changes incoming.

**Comment by huitseeker** [comment]
For people like me who are looking, @crockpotveggies means https://github.com/deeplearning4j/DataVec/pull/233/ is a prerequisite.

**Comment by crockpotveggies** [comment]
Going to close this in favor of recent changes by @raver119. If you change your mind we can reopen it.

**Pull request closed without merging**
