### PR TITLE
WIP: Programming guide

### PR DESCRIPTION
**Pull request by crockpotveggies**
## What changes were proposed in this pull request?

This branch tracks progress on the programming guide. Use this PR to track changes and leave notes.

@bpark738 note I've left notes as HTML comments in `<!-- -->` blocks. Another thing: we need to fix some of the markdown formatting. Code snippets need to have preceding tabs removed and be wrapped in triple backticks.

### CODE REVIEW

**Comment by chrisvnicholson** [comment]
I'd like to make sure we're formatting these markdown files right. 

First, at the head of every file, you need the four lines below. The content of the title line will vary, of course. The triple dash characters need to be included, and you can't just use any dashes. I recommend you just copy and past the ones I used in the intro.md file. 

---
title: DeepLearning4j Introduction
layout: default
---

Secondly, let's use internal links to help people navigate these documents. If you go into the intro.md file, you'll see how I did it:

https://github.com/deeplearning4j/deeplearning4j/blob/gh-pages/programmingguide/dl4j_intro.md

Thirdly,  code or output from a terminal should be displayed differently from normal text. For multiple lines, you can just tab each one in until it changes to gray in the editable markdown file. For one word or a brief snippet, you can bracket it with the ` character, which is under the tilde on the upper left hand side of a mac keyboard, fwiw.

**Comment by crockpotveggies** [comment]
ping @bpark738. Also, let's use this programming_guide branch to track changes before merging into gh-pages.

**Comment by chrisvnicholson** [comment]
Also, if we have a clear flow from one page of the programming guide to the next, let's put a link at the bottom of each page to the next one the reader should click to.

**Comment by bpark738** [comment]
@chrisvnicholson Hey I noticed that for some of the titles you formatted them something like this in intro.md ## <a name="java">Java</a>. Should this be done for all the titles?

**Comment by tomthetrainer** [comment]
Going further on the example Chris provided.

We should have templates or at least one template for content.

There may be a need for multiple templates, for example.

A document on a feature in dl4j, a document on a concept important for
general use, a document on an overview topic that is generally informative.


We have a template here.

https://deeplearning4j.org/doc_templates/template_basic

It has more or less the structure Chris used in Intro, but a little more
explicit.

Topic,
Summary
TOC
content 1
content 2
content 3

Etc.

**Comment by tomthetrainer** [comment]
Self managing this, one page links to another is going to be a challenge.

Either we script it somehow, or we look into a document management tool
that handles that for us.

For now we can manage by hand, but long term an investment into some tool
would be useful.

**Pull request merged**
