### PR TITLE
Update copyright headers

### PR DESCRIPTION
**Pull request by sshepel**
Please, check thoroughly, there could be a chance that smth is missing, or added unintentionally.

List of files that were not changed because of it controversial content:

1. deeplearning4j/datavec/datavec-api/src/main/java/org/datavec/api/records/reader/impl/csv/SerializableCSVParser.java
2. deeplearning4j/deeplearning4j/deeplearning4j-nlp-parent/deeplearning4j-nlp-japanese/src/main/java/com/atilika/kuromoji
3. deeplearning4j/nd4j/nd4j-common/src/main/java/org/nd4j/util/FingerPrintKeyer.java
4. deeplearning4j/libnd4j/include/ops/declarable/generic/parity_ops/space_to_batch.cpp
5. deeplearning4j/libnd4j/include/ops/declarable/generic/parity_ops/strided_slice.cpp

### CODE REVIEW

**Comment by AlexDBlack** [comment]
This might take a while to get through. I'll update this post as I work through things

**Arbiter**: reviewed, looks OK. There's no 3rd party code that I'm aware of



**DataVec**:  Some things which I wasn't aware of until now, but look suspicious:

Some content in ```org.datavec.api.io.*```
After googling the comments, looks like these might have come from Hadoop originally from Canova (which later became Datavec)

https://github.com/deeplearning4j/deeplearning4j/blob/6e26529143d51934d7a3fa24cb2af0b1436b1544/datavec/datavec-api/src/main/java/org/datavec/api/io/RawComparator.java
https://hadoop.apache.org/docs/r1.0.4/api/org/apache/hadoop/io/RawComparator.html

https://github.com/deeplearning4j/deeplearning4j/blob/6e26529143d51934d7a3fa24cb2af0b1436b1544/datavec/datavec-api/src/main/java/org/datavec/api/io/DataInputBuffer.java
https://hadoop.apache.org/docs/r1.0.4/api/index.html?org/apache/hadoop/io/DataInputBuffer.html

Same with: https://github.com/deeplearning4j/deeplearning4j/tree/6e26529143d51934d7a3fa24cb2af0b1436b1544/datavec/datavec-api/src/main/java/org/datavec/api/io/serializers

And some of (Buffer and Index at least, not sure about the others. Record and SequenceRecord are ours though):
https://github.com/deeplearning4j/deeplearning4j/tree/6e26529143d51934d7a3fa24cb2af0b1436b1544/datavec/datavec-api/src/main/java/org/datavec/api/records

Otherwise datavec looks OK

**Comment by saudet** [comment]
Thanks Alex! Though, we should wait to merge this PR only if it breaks the build, the tests, or the code in general in some way. Otherwise we'll end up having to resolve merge conflicts again and again because I'm sure there is much refinement to be done for the licensing. So, I guess we should be tracking that with an issue... Let's move your findings to a new issue?

**Comment by AlexDBlack** [comment]
@saudet Done: https://github.com/deeplearning4j/deeplearning4j/issues/5878

**Comment by saudet** [comment]
Let's rebase and see if it builds now @sshepel

**Comment by sshepel** [comment]
@saudet in general build log looks good, even though there are some `nd4j` tests failures.

**Comment by saudet** [comment]
@sshepel No new failures, only the usual ones, right?

**Pull request merged**
