### PR TITLE
Small fixes for copyright headers and libnd4j pom.xml

### PR DESCRIPTION
**Pull request by sshepel**

### CODE REVIEW

**Comment by sshepel** [comment]
@saudet but I fixed that formatting with IntelliJ IDEA (it supports Scala files), so I think it's smth else broke that formatting...
So, lets try to fix that this time, but if it will happen again will ignore it...

**Comment by saudet** [comment]
Run the build, the formatter will format it back, and then update your branch!

**Comment by sshepel** [comment]
@saudet have just did that, looks good, there is no any changes in headers.
What formatter are you referring to?

**Comment by saudet** [comment]
This one: https://github.com/deeplearning4j/deeplearning4j/blob/master/scalnet/pom.xml#L190-L205

**Comment by sshepel** [comment]
Ok, got it, fixed (remove scalnet changes from PR).

**Pull request merged**
