### PR TITLE
Add InputStream support for WordVectorSerializer [WIP]

### PR DESCRIPTION
**Pull request by AlexDBlack**
Replaces PR: https://github.com/eclipse/deeplearning4j/pull/8661

### CODE REVIEW

**Comment by hosuaby** [comment]
@AlexDBlack No problem. Thanks for help. I still need this feature

**Comment by AlexDBlack** [comment]
Unfortunately there are multiple test failures here - for example WordVectorSerializerTest in deeplearning4j-nlp-uima
This will need a closer look and some fixes before it can be merged. I believe some of the assumptions (such as single file in a zip) is incorrect in practice.

**Comment by hosuaby** [comment]
@AlexDBlack Ok. I will fix those tests and complete this PR

**Comment by hosuaby** [comment]
Hello @AlexDBlack . I checked this PR and fixed all tests (and add some more). I found this branch quite messy, with a lot of merge from master, so I took my original branch, fixed broken tests, applyed your refactorings, squashed it all I made you a new pull request, clean and shiny:
https://github.com/eclipse/deeplearning4j/pull/8908

**Comment by AlexDBlack** [comment]
Closing this - to be merged via: https://github.com/eclipse/deeplearning4j/pull/8908

**Pull request closed without merging**
