### PR TITLE
Fix up test to use right overload (object arrays)

### PR DESCRIPTION
**Pull request by agibsonccc**
## What changes were proposed in this pull request?
Follow up to: https://github.com/eclipse/deeplearning4j/pull/9333

This fixes an issue identified in this pull request and makes the test call the method with the right signature.
(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

## Quick checklist

The following checklist helps ensure your PR is complete:

- [ X] Eclipse Contributor Agreement signed, and signed commits - see [IP Requirements](https://deeplearning4j.org/eclipse-contributors) page for details
- [X ] Reviewed the [Contributing Guidelines](https://github.com/eclipse/deeplearning4j/blob/master/CONTRIBUTING.md) and followed the steps within.
- [X ] Created tests for any significant new code additions.
- [ X] Relevant tests for your changes are passing.

### CODE REVIEW

**Comment by agibsonccc** [comment]
@jljljl JFYI, the issue was compiling this on jdk 8. I'll work on a fix for this. We still have to support jdk 8 for quite a while so all testing should happen on that.

**Comment by jljljl** [comment]
@agibsonccc what's wrong?

**Comment by jljljl** [comment]
@agibsonccc here is a better way to do such changes i guess. But i cannot install whole workspace properly to find all the method invokations.

**Review by treo — APPROVED** [review]

**Comment by agibsonccc** [comment]
@jljljl JDK 8 couldn't infer the types and needed an explicit cast on the method invocation. That explains the error I was seeing. I assume you might have been testing on a newer java version. This came up when I was writing tests. It's not a big deal, it's worth noting for next time that's all. The code still works well! We just needed a bit more for jdk 8 compatibility.

**Pull request merged**
